const Job = require('../models/Job');
const { memoryStore } = require('./db');

const SAMPLE_JOBS = [
  {
    _id: 'j1',
    title: 'Senior Full Stack Software Engineer',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1000000,
    maxSalary: 1600000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 540,
    applicantsCount: 34,
    description: 'Join Infovalley IT Hub in Bhubaneswar! Apex Infotech is hiring Senior Full Stack React & Node.js Developers for enterprise cloud platforms.',
    responsibilities: [
      'Build responsive frontend user interfaces using React & Next.js',
      'Architect robust REST & GraphQL microservices in Node.js & Express',
      'Optimize database schema and query performance in MongoDB'
    ],
    requirements: [
      '3+ years professional experience with React & Node.js',
      'Proficiency in RESTful APIs, Git, and Docker'
    ],
    benefits: ['₹10 - 16 LPA Annual Package', 'Comprehensive Health Insurance', 'Flexible Hybrid Work'],
    skills: ['React', 'Node.js', 'JavaScript', 'MongoDB', 'Express'],
    applyLink: 'https://apexinfotech.co.in/careers/fullstack-eng',
    createdAt: new Date('2026-02-20T08:00:00Z')
  },
  {
    _id: 'j2',
    title: 'Junior Web Developer Trainee',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Cuttack, Cuttack, Odisha',
    state: 'Odisha',
    district: 'Cuttack',
    city: 'Cuttack',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 25000,
    maxSalary: 45000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 680,
    applicantsCount: 52,
    description: 'Great career start for fresh computer science graduates in Cuttack! Junior React frontend trainee position with structured mentoring.',
    responsibilities: [
      'Assist senior software engineers in writing clean JavaScript/React code',
      'Debug UI bugs and implement responsive web components'
    ],
    requirements: [
      'B.Tech / BCA / B.Sc in Computer Science or equivalent',
      'Knowledge of HTML5, CSS3, JavaScript ES6'
    ],
    benefits: ['₹25,000 - ₹45,000 /month stipend', 'Mentorship & Paid Certification'],
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    applyLink: 'https://apexinfotech.co.in/careers/junior-dev',
    createdAt: new Date('2026-02-21T09:30:00Z')
  },
  {
    _id: 'j3',
    title: 'Plant Operations & Metallurgical Lead',
    companyName: 'Utkal Minerals & Industrial Logistics',
    companyLogo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Rourkela, Sundargarh, Odisha',
    state: 'Odisha',
    district: 'Sundargarh (Rourkela HQ)',
    city: 'Rourkela',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 900000,
    maxSalary: 1500000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 380,
    applicantsCount: 19,
    description: 'Hiring Operations Lead at Rourkela Industrial Complex to manage steel manufacturing operations and quality compliance.',
    responsibilities: [
      'Supervise plant operations and steel furnace production shifts',
      'Enforce industrial safety and equipment maintenance standards'
    ],
    requirements: [
      'B.Tech in Metallurgical or Mechanical Engineering',
      '4+ years plant management experience in Odisha steel sector'
    ],
    benefits: ['₹9 - 15 LPA Salary + Accommodation Quarters in Rourkela'],
    skills: ['Manufacturing', 'Operations', 'Metallurgy', 'Plant Management'],
    applyLink: 'https://utkalminerals.co.in/careers/plant-lead',
    createdAt: new Date('2026-02-18T10:00:00Z')
  },
  {
    _id: 'j4',
    title: 'Senior ICU Clinical Care Nurse',
    companyName: 'Kalinga Healthcare & Medical',
    companyLogo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Cuttack, Cuttack, Odisha',
    state: 'Odisha',
    district: 'Cuttack',
    city: 'Cuttack',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 45000,
    maxSalary: 75000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 15,
    description: 'Kalinga Healthcare Super Specialty Hospital in Cuttack is hiring Senior ICU Nurses for acute medical intervention.',
    responsibilities: [
      'Monitor cardiac ICU patients and manage life support systems',
      'Administer prescribed medications and record patient vital signs'
    ],
    requirements: [
      'B.Sc Nursing / GNM with Odisha Nursing Council registration',
      '2+ years ICU experience'
    ],
    benefits: ['₹45,000 - ₹75,000 /month + shift incentives'],
    skills: ['Patient Care', 'ICU', 'BLS Certified', 'Nursing'],
    applyLink: 'https://kalingahealthcare.co.in/careers/icu-nurse',
    createdAt: new Date('2026-02-16T11:00:00Z')
  },
  {
    _id: 'j5',
    title: 'Customer Service & Helpdesk Specialist',
    companyName: 'TechConnect Customer Care',
    companyLogo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 18000,
    maxSalary: 32000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 710,
    applicantsCount: 64,
    description: 'Hiring 50 Customer Support Executives in Bhubaneswar for voice & email support desk operations.',
    responsibilities: [
      'Assist domestic customers over phone and chat in English & Odia',
      'Resolve customer service queries and escalate complex tickets'
    ],
    requirements: [
      'Higher Secondary (10+2) or Any Graduate',
      'Good verbal communication skills in English & Odia / Hindi'
    ],
    benefits: ['₹18,000 - ₹32,000 /month + PF + Medical Insurance'],
    skills: ['Customer Support', 'Communication', 'CRM', 'Helpdesk'],
    applyLink: 'https://techconnect.co.in/careers/bpo-exec',
    createdAt: new Date('2026-02-22T08:30:00Z')
  },
  {
    _id: 'j6',
    title: 'Retail Store & Sales Supervisor',
    companyName: 'Sun Retail & Lifestyle',
    companyLogo: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=150&auto=format&fit=crop&q=80',
    category: 'Hospitality & Retail',
    location: 'Puri, Puri, Odisha',
    state: 'Odisha',
    district: 'Puri',
    city: 'Puri',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 16000,
    maxSalary: 28000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 320,
    applicantsCount: 24,
    description: 'Manage flagship retail showroom in Puri town. Oversee billing counters, product merchandising, and inventory.',
    responsibilities: [
      'Maintain store inventory stock register',
      'Assist customers with billing and product recommendations'
    ],
    requirements: ['12th Pass / Diploma in Retail'],
    benefits: ['₹16,000 - ₹28,000 /month + Monthly Sales Incentives'],
    skills: ['Retail Sales', 'Billing', 'Customer Service', 'Inventory'],
    applyLink: 'https://sunretail.in/jobs/puri-supervisor',
    createdAt: new Date('2026-02-19T14:15:00Z')
  },
  {
    _id: 'j7',
    title: 'Heavy Freight & Logistics Hub Manager',
    companyName: 'Utkal Minerals & Industrial Logistics',
    companyLogo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    category: 'Logistics & Supply Chain',
    location: 'Jharsuguda, Jharsuguda, Odisha',
    state: 'Odisha',
    district: 'Jharsuguda',
    city: 'Jharsuguda',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 700000,
    maxSalary: 1100000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 240,
    applicantsCount: 14,
    description: 'Manage cargo freight sidings and heavy transport vehicle dispatch at Jharsuguda logistics hub.',
    responsibilities: [
      'Coordinate railway siding freight loads and truck fleets',
      'Ensure compliance with transport documentation and safety'
    ],
    requirements: ['Degree/Diploma in Supply Chain or Logistics'],
    benefits: ['₹7 - 11 LPA Annual Pay + Fleet Bonus'],
    skills: ['Logistics', 'Supply Chain', 'Freight Management', 'Operations'],
    applyLink: 'https://utkalminerals.co.in/careers/jharsuguda-logistics',
    createdAt: new Date('2026-02-17T12:00:00Z')
  },
  {
    _id: 'j8',
    title: 'Frontend React Developer',
    companyName: 'CloudCraft Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1200000,
    maxSalary: 1800000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 890,
    applicantsCount: 78,
    description: 'Building high scale SaaS applications in Indiranagar, Bengaluru. Looking for strong React, TypeScript, and Redux Engineers.',
    responsibilities: [
      'Develop modern SPA web apps in React 18 & TypeScript',
      'Optimize web vitals, state management, and reusable UI components'
    ],
    requirements: ['3+ years React & TypeScript experience'],
    benefits: ['₹12 - 18 LPA + Stock Options + Flexible Hybrid'],
    skills: ['React', 'TypeScript', 'Redux', 'TailwindCSS'],
    applyLink: 'https://cloudcraft.dev/careers/react-eng',
    createdAt: new Date('2026-02-21T10:00:00Z')
  },
  {
    _id: 'j9',
    title: 'DevOps & Cloud Infrastructure Engineer',
    companyName: 'CloudCraft Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Remote',
    jobType: 'Remote',
    experienceLevel: 'Senior Level',
    minSalary: 1500000,
    maxSalary: 2400000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 650,
    applicantsCount: 45,
    description: 'Remote AWS & Kubernetes DevOps role. Architect CI/CD pipelines, Docker containers, and infrastructure as code.',
    responsibilities: [
      'Manage AWS ECS, EKS, Terraform scripts, and CI/CD pipelines',
      'Maintain 99.99% cloud service uptime'
    ],
    requirements: ['AWS Certified Solutions Architect + Docker/Kubernetes'],
    benefits: ['₹15 - 24 LPA + 100% Work From Anywhere'],
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    applyLink: 'https://cloudcraft.dev/careers/devops-sr',
    createdAt: new Date('2026-02-22T11:00:00Z')
  },
  {
    _id: 'j10',
    title: 'Senior Java Backend Developer',
    companyName: 'CyberTech India Systems',
    companyLogo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 1400000,
    maxSalary: 2200000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 580,
    applicantsCount: 39,
    description: 'Hiring Senior Java Spring Boot Developers in HITEC City, Hyderabad for high-throughput banking payment gateways.',
    responsibilities: [
      'Design Java Spring Boot microservices and REST endpoints',
      'Optimize PostgreSQL & Kafka message streaming'
    ],
    requirements: ['5+ years Core Java & Spring Boot experience'],
    benefits: ['₹14 - 22 LPA + Joining Bonus'],
    skills: ['Java', 'Spring Boot', 'Microservices', 'Kafka', 'PostgreSQL'],
    applyLink: 'https://cybertech.co.in/careers/java-backend',
    createdAt: new Date('2026-02-15T09:00:00Z')
  },
  {
    _id: 'j11',
    title: 'Financial Data Analyst',
    companyName: 'FinGlobal Systems',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Mumbai, Mumbai City, Maharashtra',
    state: 'Maharashtra',
    district: 'Mumbai City',
    city: 'Mumbai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 800000,
    maxSalary: 1400000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 420,
    applicantsCount: 28,
    description: 'Analyze financial markets, portfolio metrics, and risk management models in BKC, Mumbai.',
    responsibilities: [
      'Build financial forecast dashboards in PowerBI & Python',
      'Analyze quarterly P&L and investment risk indicators'
    ],
    requirements: ['MBA Finance / CFA / B.Sc Statistics with SQL & Python'],
    benefits: ['₹8 - 14 LPA + Annual Performance Bonus'],
    skills: ['Financial Analysis', 'SQL', 'Python', 'PowerBI', 'Excel'],
    applyLink: 'https://finglobal.com/careers/data-analyst',
    createdAt: new Date('2026-02-18T15:00:00Z')
  },
  {
    _id: 'j12',
    title: 'UI/UX Product Designer',
    companyName: 'DesignVerse Studio',
    companyLogo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 750000,
    maxSalary: 1300000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 390,
    applicantsCount: 31,
    description: 'Create user journeys, wireframes, and design systems for web & mobile applications in Pune.',
    responsibilities: [
      'Design high fidelity interactive prototypes in Figma',
      'Conduct usability testing sessions with end users'
    ],
    requirements: ['2+ years UI/UX design portfolio in Figma'],
    benefits: ['₹7.5 - 13 LPA + Ergonomic Desk Allowance'],
    skills: ['Figma', 'UI/UX', 'Wireframing', 'Prototyping', 'Design System'],
    applyLink: 'https://designverse.io/careers/uiux-designer',
    createdAt: new Date('2026-02-20T16:30:00Z')
  },
  {
    _id: 'j13',
    title: 'Digital Marketing & SEO Specialist',
    companyName: 'GrowthPulse India',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'Noida, Gautam Buddha Nagar, Uttar Pradesh',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar (Noida)',
    city: 'Noida',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 30000,
    maxSalary: 55000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 490,
    applicantsCount: 41,
    description: 'Lead Google Ads, Meta ad campaigns, organic SEO ranking, and content strategy in Sector 62, Noida.',
    responsibilities: [
      'Execute Google Pay-Per-Click campaigns and SEO keyword audits',
      'Manage company social media handles and lead generation channels'
    ],
    requirements: ['Digital Marketing Certification / 1+ years PPC experience'],
    benefits: ['₹30,000 - ₹55,000 /month + Campaign Bonus'],
    skills: ['SEO', 'Google Ads', 'Meta Ads', 'Content Marketing', 'Analytics'],
    applyLink: 'https://growthpulse.in/jobs/seo-specialist',
    createdAt: new Date('2026-02-14T10:00:00Z')
  },
  {
    _id: 'j14',
    title: 'Business Operations Associate',
    companyName: 'GrowthPulse India',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Gurugram, Haryana',
    state: 'Haryana',
    district: 'Gurugram',
    city: 'Gurugram',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 28000,
    maxSalary: 48000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 360,
    applicantsCount: 29,
    description: 'Manage daily client onboarding, vendor relations, and operational reports in Cyber City, Gurugram.',
    responsibilities: [
      'Assist operations team with client documentation and SLA compliance',
      'Prepare weekly MIS reports using Advanced Excel'
    ],
    requirements: ['Graduate degree with strong MS Excel skills'],
    benefits: ['₹28,000 - ₹48,000 /month'],
    skills: ['Operations', 'MS Excel', 'Communication', 'MIS Reporting'],
    applyLink: 'https://growthpulse.in/jobs/ops-associate',
    createdAt: new Date('2026-02-16T13:00:00Z')
  },
  {
    _id: 'j15',
    title: 'Full Stack Python & Django Developer',
    companyName: 'AI Systems India',
    companyLogo: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'New Delhi, Delhi NCR',
    state: 'Delhi NCR',
    district: 'New Delhi',
    city: 'New Delhi',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1100000,
    maxSalary: 1700000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 510,
    applicantsCount: 36,
    description: 'Develop AI & Machine Learning web portals using Python, Django, REST Framework, and React in Connaught Place, New Delhi.',
    responsibilities: [
      'Write scalable Python microservices integrated with OpenAI & PyTorch models',
      'Build React frontend components consuming Django REST APIs'
    ],
    requirements: ['3+ years Python & Django experience'],
    benefits: ['₹11 - 17 LPA + AI Training Sponsorship'],
    skills: ['Python', 'Django', 'React', 'REST API', 'PostgreSQL'],
    applyLink: 'https://aisystems.in/careers/python-django',
    createdAt: new Date('2026-02-21T09:00:00Z')
  },
  {
    _id: 'j16',
    title: 'Clinical Research Associate',
    companyName: 'Aura Pharma Labs',
    companyLogo: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 600000,
    maxSalary: 950000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 230,
    applicantsCount: 17,
    description: 'Oversee clinical trials, patient trial documentation, and regulatory compliance at Chennai lab facility.',
    responsibilities: [
      'Monitor clinical trial sites according to GCP guidelines',
      'Audit clinical data logs and trial safety reports'
    ],
    requirements: ['B.Pharm / M.Pharm / M.Sc Life Sciences'],
    benefits: ['₹6 - 9.5 LPA + Health Cover'],
    skills: ['Clinical Trials', 'GCP Guidelines', 'Pharma', 'Pharmacovigilance'],
    applyLink: 'https://aurapharma.co.in/careers/cra',
    createdAt: new Date('2026-02-15T11:00:00Z')
  },
  {
    _id: 'j17',
    title: 'Quality Assurance Automation Tester',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 700000,
    maxSalary: 1100000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 380,
    applicantsCount: 27,
    description: 'Automate web application test suites using Selenium, Cypress, and Postman API automation in Bhubaneswar.',
    responsibilities: [
      'Create automated test scripts in JavaScript/Python using Cypress',
      'Perform API integration testing and regression analysis'
    ],
    requirements: ['2+ years automation testing experience'],
    benefits: ['₹7 - 11 LPA + Skill Bonus'],
    skills: ['Cypress', 'Selenium', 'Postman', 'JavaScript', 'QA Testing'],
    applyLink: 'https://apexinfotech.co.in/careers/qa-automation',
    createdAt: new Date('2026-02-19T10:00:00Z')
  },
  {
    _id: 'j18',
    title: 'Human Resources Generalist',
    companyName: 'Kalinga HR & Talent Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Sambalpur, Sambalpur, Odisha',
    state: 'Odisha',
    district: 'Sambalpur',
    city: 'Sambalpur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 22000,
    maxSalary: 38000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 21,
    description: 'Handle employee onboarding, attendance payroll processing, and talent acquisition in Sambalpur office.',
    responsibilities: [
      'Screen candidate resumes and conduct preliminary interviews',
      'Manage monthly payroll processing and employee grievances'
    ],
    requirements: ['MBA HR / BBA Graduate'],
    benefits: ['₹22,000 - ₹38,000 /month'],
    skills: ['Recruitment', 'Payroll', 'Employee Relations', 'HR Ops'],
    applyLink: 'https://kalingahr.co.in/jobs/hr-generalist',
    createdAt: new Date('2026-02-17T14:00:00Z')
  },
  {
    _id: 'j19',
    title: 'Civil Construction Site Engineer',
    companyName: 'Utkal Infrastructure & Construction',
    companyLogo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Berhampur, Ganjam, Odisha',
    state: 'Odisha',
    district: 'Ganjam (Berhampur)',
    city: 'Berhampur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 500000,
    maxSalary: 850000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 310,
    applicantsCount: 18,
    description: 'Supervise residential and commercial building construction sites in Berhampur, Ganjam district.',
    responsibilities: [
      'Oversee structural concrete pouring and building layout accuracy',
      'Manage site labor, contractor bills, and materials testing'
    ],
    requirements: ['B.Tech / Diploma in Civil Engineering'],
    benefits: ['₹5 - 8.5 LPA + Site Allowance'],
    skills: ['Civil Engineering', 'Construction Management', 'AutoCAD', 'Site Inspection'],
    applyLink: 'https://utkalinfra.co.in/careers/civil-eng',
    createdAt: new Date('2026-02-13T09:30:00Z')
  },
  {
    _id: 'j20',
    title: 'Cyber Security Operations Analyst',
    companyName: 'SecureShield India',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Ahmedabad, Gujarat',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 900000,
    maxSalary: 1500000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 460,
    applicantsCount: 32,
    description: 'Monitor network SOC security alerts, vulnerability assessments, and penetration testing in GIFT City, Ahmedabad.',
    responsibilities: [
      'Analyze network traffic logs using Splunk & Wireshark',
      'Conduct penetration testing and patch security vulnerabilities'
    ],
    requirements: ['CEH / CISSP certification + 2 years SOC experience'],
    benefits: ['₹9 - 15 LPA + Security Clearance Bonus'],
    skills: ['Cyber Security', 'Splunk', 'Penetration Testing', 'SOC', 'Network Security'],
    applyLink: 'https://secureshield.in/careers/soc-analyst',
    createdAt: new Date('2026-02-20T12:00:00Z')
  }
];

const seedDatabaseIfEmpty = async () => {
  try {
    const isMongoConnected = require('mongoose').connection.readyState === 1;

    if (isMongoConnected) {
      const count = await Job.countDocuments();
      if (count === 0) {
        console.log('Seeding MongoDB "jobs" collection with sample records...');
        const formattedJobs = SAMPLE_JOBS.map(j => {
          const { _id, ...rest } = j;
          return rest;
        });
        await Job.insertMany(formattedJobs);
        console.log(`Successfully inserted ${SAMPLE_JOBS.length} sample job records into MongoDB!`);
      } else {
        console.log(`MongoDB "jobs" collection already contains ${count} records.`);
      }
    } else {
      // In-Memory store check
      if (!memoryStore.jobs || memoryStore.jobs.length < 10) {
        console.log('Populating in-memory store with 20 sample job records...');
        memoryStore.jobs = [...SAMPLE_JOBS];
        console.log(`In-memory store now contains ${memoryStore.jobs.length} jobs.`);
      }
    }
  } catch (err) {
    console.error('Error seeding database jobs:', err.message);
  }
};

module.exports = { SAMPLE_JOBS, seedDatabaseIfEmpty };
