const Job = require('../models/Job');
const { memoryStore } = require('./db');

const UNIQUE_55_JOBS = [
  // 1. Technology & IT (12)
  {
    _id: 'j1',
    title: 'Senior Full Stack Software Engineer',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1000000,
    maxSalary: 1600000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 540,
    applicantsCount: 34,
    description: 'Join Infovalley IT Hub in Bhubaneswar! Apex Infotech is hiring Senior Full Stack React & Node.js Developers for enterprise cloud platforms.',
    responsibilities: ['Develop frontend React interfaces', 'Build Node.js microservices', 'Optimize MongoDB performance'],
    requirements: ['3+ years React & Node.js experience'],
    benefits: ['₹10 - 16 LPA Annual Package', 'Family Health Cover'],
    skills: ['React', 'Node.js', 'JavaScript', 'MongoDB', 'Express'],
    applyLink: 'https://apexinfotech.co.in/careers/fullstack-eng',
    createdAt: new Date('2026-02-20T08:00:00Z')
  },
  {
    _id: 'j2',
    title: 'Junior Web Developer Trainee',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Cuttack, Cuttack, Odisha',
    state: 'Odisha',
    district: 'Cuttack',
    city: 'Cuttack',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 25000,
    maxSalary: 45000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 680,
    applicantsCount: 52,
    description: 'Great career start for fresh computer science graduates in Cuttack! Junior React frontend trainee position with structured mentoring.',
    responsibilities: ['Assist senior developers', 'Fix UI bugs', 'Build responsive layouts'],
    requirements: ['B.Tech / BCA with HTML, CSS, JavaScript'],
    benefits: ['₹25,000 - ₹45,000 /month stipend'],
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    applyLink: 'https://apexinfotech.co.in/careers/junior-dev',
    createdAt: new Date('2026-02-21T09:30:00Z')
  },
  {
    _id: 'j3',
    title: 'Frontend React Developer',
    companyName: 'CloudCraft Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1200000,
    maxSalary: 1800000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 890,
    applicantsCount: 78,
    description: 'Building high scale SaaS applications in Indiranagar, Bengaluru. Looking for strong React, TypeScript, and Redux Engineers.',
    responsibilities: ['Develop SPA apps in React 18', 'Optimize Web Vitals'],
    requirements: ['3+ years React & TypeScript experience'],
    benefits: ['₹12 - 18 LPA + Stock Options'],
    skills: ['React', 'TypeScript', 'Redux', 'TailwindCSS'],
    applyLink: 'https://cloudcraft.dev/careers/react-eng',
    createdAt: new Date('2026-02-21T10:00:00Z')
  },
  {
    _id: 'j4',
    title: 'DevOps & Cloud Infrastructure Lead',
    companyName: 'CloudCraft Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Remote',
    jobType: 'Remote',
    experienceLevel: 'Senior Level',
    minSalary: 1500000,
    maxSalary: 2400000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 650,
    applicantsCount: 45,
    description: 'Remote AWS & Kubernetes DevOps role. Architect CI/CD pipelines, Docker containers, and infrastructure as code.',
    responsibilities: ['Manage AWS ECS, EKS, Terraform scripts', 'Ensure 99.99% uptime'],
    requirements: ['AWS Certified Solutions Architect + Docker/Kubernetes'],
    benefits: ['₹15 - 24 LPA + 100% Remote'],
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    applyLink: 'https://cloudcraft.dev/careers/devops-sr',
    createdAt: new Date('2026-02-22T11:00:00Z')
  },
  {
    _id: 'j5',
    title: 'Senior Java Backend Engineer',
    companyName: 'CyberTech India Systems',
    companyLogo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 1400000,
    maxSalary: 2200000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 580,
    applicantsCount: 39,
    description: 'Hiring Senior Java Spring Boot Developers in HITEC City, Hyderabad for high-throughput banking payment gateways.',
    responsibilities: ['Design Java Spring Boot microservices', 'Optimize Kafka streams'],
    requirements: ['5+ years Core Java & Spring Boot'],
    benefits: ['₹14 - 22 LPA + Joining Bonus'],
    skills: ['Java', 'Spring Boot', 'Microservices', 'Kafka', 'PostgreSQL'],
    applyLink: 'https://cybertech.co.in/careers/java-backend',
    createdAt: new Date('2026-02-15T09:00:00Z')
  },
  {
    _id: 'j6',
    title: 'Full Stack Python & Django Developer',
    companyName: 'AI Systems India',
    companyLogo: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'New Delhi, Delhi NCR',
    state: 'Delhi NCR',
    district: 'New Delhi',
    city: 'New Delhi',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1100000,
    maxSalary: 1700000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 510,
    applicantsCount: 36,
    description: 'Develop AI & Machine Learning web portals using Python, Django, REST Framework, and React in Connaught Place, New Delhi.',
    responsibilities: ['Write Python microservices', 'Integrate OpenAI APIs'],
    requirements: ['3+ years Python & Django experience'],
    benefits: ['₹11 - 17 LPA + AI Training Sponsorship'],
    skills: ['Python', 'Django', 'React', 'REST API', 'PostgreSQL'],
    applyLink: 'https://aisystems.in/careers/python-django',
    createdAt: new Date('2026-02-21T09:00:00Z')
  },
  {
    _id: 'j7',
    title: 'Quality Assurance Automation Tester',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 700000,
    maxSalary: 1100000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 380,
    applicantsCount: 27,
    description: 'Automate web application test suites using Selenium, Cypress, and Postman API automation in Bhubaneswar.',
    responsibilities: ['Create automated Cypress scripts', 'Perform regression testing'],
    requirements: ['2+ years automation testing experience'],
    benefits: ['₹7 - 11 LPA + Skill Bonus'],
    skills: ['Cypress', 'Selenium', 'Postman', 'JavaScript', 'QA Testing'],
    applyLink: 'https://apexinfotech.co.in/careers/qa-automation',
    createdAt: new Date('2026-02-19T10:00:00Z')
  },
  {
    _id: 'j8',
    title: 'Cyber Security Operations Analyst',
    companyName: 'SecureShield India',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Ahmedabad, Gujarat',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 900000,
    maxSalary: 1500000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 460,
    applicantsCount: 32,
    description: 'Monitor network SOC security alerts, vulnerability assessments, and penetration testing in GIFT City, Ahmedabad.',
    responsibilities: ['Analyze Splunk logs', 'Conduct penetration testing'],
    requirements: ['CEH / CISSP certification + SOC experience'],
    benefits: ['₹9 - 15 LPA + Security Bonus'],
    skills: ['Cyber Security', 'Splunk', 'Penetration Testing', 'SOC'],
    applyLink: 'https://secureshield.in/careers/soc-analyst',
    createdAt: new Date('2026-02-20T12:00:00Z')
  },
  {
    _id: 'j9',
    title: 'Flutter & React Native Mobile App Developer',
    companyName: 'AppStudio Labs',
    companyLogo: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Kochi, Ernakulam, Kerala',
    state: 'Kerala',
    district: 'Ernakulam (Kochi)',
    city: 'Kochi',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 800000,
    maxSalary: 1400000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 410,
    applicantsCount: 29,
    description: 'Build cross-platform Android & iOS applications using Flutter and React Native in Infopark Kochi.',
    responsibilities: ['Publish apps to Play Store & App Store', 'Integrate push notifications & REST APIs'],
    requirements: ['2+ years Flutter / React Native experience'],
    benefits: ['₹8 - 14 LPA + Relocation Allowance'],
    skills: ['Flutter', 'React Native', 'Dart', 'iOS', 'Android'],
    applyLink: 'https://appstudio.io/careers/mobile-dev',
    createdAt: new Date('2026-02-18T14:00:00Z')
  },
  {
    _id: 'j10',
    title: 'Data Engineer & ETL Pipeline Lead',
    companyName: 'DataEdge Systems',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 1300000,
    maxSalary: 2000000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 370,
    applicantsCount: 24,
    description: 'Design enterprise Big Data data warehouses, PySpark pipelines, and Snowflake data models in Hinjewadi, Pune.',
    responsibilities: ['Build Spark & Airflow DAGs', 'Maintain Snowflake data warehouse'],
    requirements: ['Python, PySpark, SQL, Airflow expertise'],
    benefits: ['₹13 - 20 LPA + Performance Bonus'],
    skills: ['Python', 'PySpark', 'SQL', 'Snowflake', 'Airflow'],
    applyLink: 'https://dataedge.co.in/jobs/data-eng-lead',
    createdAt: new Date('2026-02-17T16:00:00Z')
  },
  {
    _id: 'j11',
    title: 'Salesforce Cloud Administrator',
    companyName: 'CRM Solutions India',
    companyLogo: 'https://images.unsplash.com/photo-1542744896-6a31c08764b8?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Gurugram, Haryana',
    state: 'Haryana',
    district: 'Gurugram',
    city: 'Gurugram',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 850000,
    maxSalary: 1350000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 340,
    applicantsCount: 22,
    description: 'Manage Salesforce Sales Cloud and Service Cloud configurations, Flow builders, and user permissions in Cyber City Gurugram.',
    responsibilities: ['Configure Salesforce Flows & Apex triggers', 'Manage CRM security roles'],
    requirements: ['Salesforce Certified Administrator ADM-201'],
    benefits: ['₹8.5 - 13.5 LPA + Certification Incentives'],
    skills: ['Salesforce', 'CRM', 'Apex', 'Flow Builder'],
    applyLink: 'https://crmsolutions.in/jobs/salesforce-admin',
    createdAt: new Date('2026-02-14T11:00:00Z')
  },
  {
    _id: 'j12',
    title: 'Embedded IoT Systems Engineer',
    companyName: 'SmartTech India Labs',
    companyLogo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=150&auto=format&fit=crop&q=80',
    category: 'Technology & IT',
    location: 'Mysuru, Mysuru, Karnataka',
    state: 'Karnataka',
    district: 'Mysuru',
    city: 'Mysuru',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 750000,
    maxSalary: 1250000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 18,
    description: 'Program STM32 microcontrollers, ESP32 Wi-Fi modules, and RTOS firmware for smart metering IoT devices in Mysuru.',
    responsibilities: ['Write Embedded C/C++ code for MCU boards', 'Perform PCB circuit testing'],
    requirements: ['B.Tech ECE / EEE with Embedded C skills'],
    benefits: ['₹7.5 - 12.5 LPA + Lab Allowance'],
    skills: ['Embedded C', 'IoT', 'ESP32', 'STM32', 'RTOS'],
    applyLink: 'https://smarttech.co.in/careers/embedded-eng',
    createdAt: new Date('2026-02-12T10:00:00Z')
  },

  // 2. Healthcare & Medical (8)
  {
    _id: 'j13',
    title: 'Senior ICU Clinical Care Nurse',
    companyName: 'Kalinga Healthcare & Medical',
    companyLogo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Cuttack, Cuttack, Odisha',
    state: 'Odisha',
    district: 'Cuttack',
    city: 'Cuttack',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 45000,
    maxSalary: 75000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 15,
    description: 'Kalinga Healthcare Super Specialty Hospital in Cuttack is hiring Senior ICU Nurses for acute medical intervention.',
    responsibilities: ['Monitor cardiac ICU patients', 'Administer prescribed medications'],
    requirements: ['B.Sc Nursing / GNM with registration'],
    benefits: ['₹45,000 - ₹75,000 /month + shift incentives'],
    skills: ['Patient Care', 'ICU', 'BLS Certified', 'Nursing'],
    applyLink: 'https://kalingahealthcare.co.in/careers/icu-nurse',
    createdAt: new Date('2026-02-16T11:00:00Z')
  },
  {
    _id: 'j14',
    title: 'Clinical Research Associate',
    companyName: 'Aura Pharma Labs',
    companyLogo: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 600000,
    maxSalary: 950000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 230,
    applicantsCount: 17,
    description: 'Oversee clinical trials, patient trial documentation, and regulatory compliance at Chennai lab facility.',
    responsibilities: ['Monitor clinical trial sites', 'Audit data logs according to GCP'],
    requirements: ['B.Pharm / M.Pharm / M.Sc Life Sciences'],
    benefits: ['₹6 - 9.5 LPA + Health Cover'],
    skills: ['Clinical Trials', 'GCP Guidelines', 'Pharma', 'Pharmacovigilance'],
    applyLink: 'https://aurapharma.co.in/careers/cra',
    createdAt: new Date('2026-02-15T11:00:00Z')
  },
  {
    _id: 'j15',
    title: 'Hospital Pharmacy Operations Specialist',
    companyName: 'Kalinga Healthcare & Medical',
    companyLogo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 35000,
    maxSalary: 60000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 310,
    applicantsCount: 20,
    description: 'Manage hospital inpatient pharmacy inventory, prescription verification, and drug safety records in Bhubaneswar.',
    responsibilities: ['Verify doctor prescriptions', 'Maintain hospital pharmacy inventory'],
    requirements: ['B.Pharm / D.Pharm with Registered Pharmacist License'],
    benefits: ['₹35,000 - ₹60,000 /month'],
    skills: ['Pharmacy', 'Prescription Verification', 'Drug Safety'],
    applyLink: 'https://kalingahealthcare.co.in/careers/pharmacist',
    createdAt: new Date('2026-02-19T09:00:00Z')
  },
  {
    _id: 'j16',
    title: 'Diagnostic Laboratory Technician',
    companyName: 'HealthPath Diagnostics',
    companyLogo: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Mumbai, Mumbai City, Maharashtra',
    state: 'Maharashtra',
    district: 'Mumbai City',
    city: 'Mumbai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 22000,
    maxSalary: 38000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 260,
    applicantsCount: 16,
    description: 'Conduct clinical blood biochemistry testing, hematology, and sample processing in Dadar, Mumbai.',
    responsibilities: ['Process blood samples on automated analyzers', 'Prepare diagnostic lab reports'],
    requirements: ['DMLT / B.Sc Medical Lab Technology'],
    benefits: ['₹22,000 - ₹38,000 /month'],
    skills: ['Pathology', 'DMLT', 'Blood Testing', 'Lab Diagnostics'],
    applyLink: 'https://healthpath.co.in/jobs/lab-tech',
    createdAt: new Date('2026-02-17T15:00:00Z')
  },
  {
    _id: 'j17',
    title: 'Pediatric Resident Physician',
    companyName: 'Apollo Clinical Care Center',
    companyLogo: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 1200000,
    maxSalary: 1800000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 390,
    applicantsCount: 14,
    description: 'Full-time Pediatric Medical Officer position overseeing inpatient pediatric ward care and vaccination protocols in Jubilee Hills.',
    responsibilities: ['Manage pediatric OPD and inpatient ward', 'Conduct pediatric emergency care'],
    requirements: ['MBBS + MD / DCH in Pediatrics'],
    benefits: ['₹12 - 18 LPA + Medical Quarters'],
    skills: ['Pediatrics', 'MBBS', 'Clinical Care', 'Emergency Medicine'],
    applyLink: 'https://apollocare.in/careers/pediatrician',
    createdAt: new Date('2026-02-20T08:30:00Z')
  },
  {
    _id: 'j18',
    title: 'Radiologist Technician (MRI & CT Scan)',
    companyName: 'Sun Medical Center',
    companyLogo: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Berhampur, Ganjam, Odisha',
    state: 'Odisha',
    district: 'Ganjam (Berhampur)',
    city: 'Berhampur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 28000,
    maxSalary: 48000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 220,
    applicantsCount: 11,
    description: 'Operate 1.5T MRI scanners, multi-slice CT scanners, and digital X-ray equipment in Berhampur hospital.',
    responsibilities: ['Perform MRI & CT scan imaging procedures', 'Ensure radiation safety standards'],
    requirements: ['Diploma/B.Sc in Radio Diagnosis Technology (DRT)'],
    benefits: ['₹28,000 - ₹48,000 /month'],
    skills: ['MRI', 'CT Scan', 'Radiology', 'X-Ray'],
    applyLink: 'https://sunmedical.co.in/jobs/radiologist-tech',
    createdAt: new Date('2026-02-13T12:00:00Z')
  },
  {
    _id: 'j19',
    title: 'Pharma Medical Sales Executive',
    companyName: 'Aura Pharma Labs',
    companyLogo: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Indore, Madhya Pradesh',
    state: 'Madhya Pradesh',
    district: 'Indore',
    city: 'Indore',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 20000,
    maxSalary: 35000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 280,
    applicantsCount: 25,
    description: 'Visit doctors, hospitals, and pharmacies in Indore to present pharmaceutical formulations and generate prescriptions.',
    responsibilities: ['Conduct doctor calls and product presentations', 'Achieve monthly sales targets'],
    requirements: ['B.Pharm / B.Sc Graduate with 2-wheeler'],
    benefits: ['₹20,000 - ₹35,000 /month + TA/DA + Commission'],
    skills: ['Medical Sales', 'Pharma Marketing', 'Communication'],
    applyLink: 'https://aurapharma.co.in/careers/mr-indore',
    createdAt: new Date('2026-02-15T16:00:00Z')
  },
  {
    _id: 'j20',
    title: 'Physical Therapy & Rehabilitation Lead',
    companyName: 'CareFirst Health',
    companyLogo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=150&auto=format&fit=crop&q=80',
    category: 'Healthcare & Medical',
    location: 'Dehradun, Uttarakhand',
    state: 'Uttarakhand',
    district: 'Dehradun',
    city: 'Dehradun',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 35000,
    maxSalary: 55000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 210,
    applicantsCount: 13,
    description: 'Treat post-surgery orthopedic patients, stroke recovery, and sports injury rehabilitation in Dehradun clinic.',
    responsibilities: ['Formulate physical therapy treatment plans', 'Conduct electrotherapy sessions'],
    requirements: ['BPT / MPT (Bachelor of Physiotherapy)'],
    benefits: ['₹35,000 - ₹55,000 /month'],
    skills: ['Physiotherapy', 'Orthopedics', 'Rehabilitation', 'BPT'],
    applyLink: 'https://carefirsthealth.in/careers/physio-lead',
    createdAt: new Date('2026-02-11T14:00:00Z')
  },

  // 3. Engineering & Manufacturing (8)
  {
    _id: 'j21',
    title: 'Plant Operations & Metallurgical Lead',
    companyName: 'Utkal Minerals & Industrial Logistics',
    companyLogo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Rourkela, Sundargarh, Odisha',
    state: 'Odisha',
    district: 'Sundargarh (Rourkela HQ)',
    city: 'Rourkela',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 900000,
    maxSalary: 1500000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 380,
    applicantsCount: 19,
    description: 'Hiring Operations Lead at Rourkela Industrial Complex to manage steel manufacturing operations and quality compliance.',
    responsibilities: ['Supervise plant operations', 'Enforce safety standards'],
    requirements: ['B.Tech Metallurgical or Mechanical'],
    benefits: ['₹9 - 15 LPA + Quarters in Rourkela'],
    skills: ['Manufacturing', 'Operations', 'Metallurgy', 'Plant Management'],
    applyLink: 'https://utkalminerals.co.in/careers/plant-lead',
    createdAt: new Date('2026-02-18T10:00:00Z')
  },
  {
    _id: 'j22',
    title: 'Civil Construction Site Engineer',
    companyName: 'Utkal Infrastructure & Construction',
    companyLogo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Berhampur, Ganjam, Odisha',
    state: 'Odisha',
    district: 'Ganjam (Berhampur)',
    city: 'Berhampur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 500000,
    maxSalary: 850000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 310,
    applicantsCount: 18,
    description: 'Supervise residential and commercial building construction sites in Berhampur, Ganjam district.',
    responsibilities: ['Oversee concrete pouring', 'Manage site labor and billing'],
    requirements: ['B.Tech / Diploma in Civil Engineering'],
    benefits: ['₹5 - 8.5 LPA + Site Allowance'],
    skills: ['Civil Engineering', 'Construction Management', 'AutoCAD'],
    applyLink: 'https://utkalinfra.co.in/careers/civil-eng',
    createdAt: new Date('2026-02-13T09:30:00Z')
  },
  {
    _id: 'j23',
    title: 'Senior Mechanical Design Engineer',
    companyName: 'Tata Precision Engineering',
    companyLogo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Jamshedpur, Jharkhand',
    state: 'Jharkhand',
    district: 'East Singhbhum (Jamshedpur)',
    city: 'Jamshedpur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 1100000,
    maxSalary: 1700000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 420,
    applicantsCount: 26,
    description: 'Design heavy machinery components, CAD 3D models, and stress analysis in Jamshedpur industrial plant.',
    responsibilities: ['Create SolidWorks & CATIA 3D models', 'Perform FEA stress analysis'],
    requirements: ['B.Tech Mechanical + SolidWorks expertise'],
    benefits: ['₹11 - 17 LPA + Tata Quarters'],
    skills: ['SolidWorks', 'CATIA', 'FEA', 'Mechanical Engineering'],
    applyLink: 'https://tataprecision.com/jobs/mechanical-sr',
    createdAt: new Date('2026-02-19T11:00:00Z')
  },
  {
    _id: 'j24',
    title: 'Electrical Systems Maintenance Lead',
    companyName: 'SteelCraft Industries',
    companyLogo: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Bhilai, Durg, Chhattisgarh',
    state: 'Chhattisgarh',
    district: 'Durg (Bhilai)',
    city: 'Bhilai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 600000,
    maxSalary: 950000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 270,
    applicantsCount: 16,
    description: 'Maintain 33kV high voltage transformers, PLC panels, and industrial motors at Bhilai plant.',
    responsibilities: ['Supervise electrical panel maintenance', 'Troubleshoot Siemens PLC systems'],
    requirements: ['B.Tech / Diploma EEE + Electrical Supervisory License'],
    benefits: ['₹6 - 9.5 LPA'],
    skills: ['PLC', 'Electrical Maintenance', 'Transformers', 'Automation'],
    applyLink: 'https://steelcraft.co.in/careers/electrical-lead',
    createdAt: new Date('2026-02-15T13:00:00Z')
  },
  {
    _id: 'j25',
    title: 'Automotive Production Assembly Supervisor',
    companyName: 'AutoTech Manufacturing',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 550000,
    maxSalary: 900000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 310,
    applicantsCount: 21,
    description: 'Oversee robot assembly line shifts and quality assurance checks for passenger vehicles in Oragadam, Chennai.',
    responsibilities: ['Ensure hourly assembly targets', 'Implement Kaizen & 5S shopfloor practices'],
    requirements: ['Diploma / B.Tech Production / Automobile Engineering'],
    benefits: ['₹5.5 - 9 LPA + Shift Allowance'],
    skills: ['Automotive', 'Assembly Line', 'Kaizen', 'Manufacturing'],
    applyLink: 'https://autotech.co.in/jobs/assembly-sup',
    createdAt: new Date('2026-02-14T15:00:00Z')
  },
  {
    _id: 'j26',
    title: 'Industrial Safety & EHS Officer',
    companyName: 'Utkal Minerals & Industrial Logistics',
    companyLogo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Jharsuguda, Jharsuguda, Odisha',
    state: 'Odisha',
    district: 'Jharsuguda',
    city: 'Jharsuguda',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 40000,
    maxSalary: 65000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 240,
    applicantsCount: 14,
    description: 'Conduct industrial hazard audits, PPE safety inspections, and pollution control compliance in Jharsuguda plant.',
    responsibilities: ['Conduct daily safety toolbox talks', 'Investigate plant safety incidents'],
    requirements: ['Diploma in Industrial Safety (NEBOSH / RLI)'],
    benefits: ['₹40,000 - ₹65,000 /month'],
    skills: ['Safety Audit', 'NEBOSH', 'EHS', 'Industrial Safety'],
    applyLink: 'https://utkalminerals.co.in/careers/ehs-officer',
    createdAt: new Date('2026-02-17T12:00:00Z')
  },
  {
    _id: 'j27',
    title: 'Chemical Process Safety Engineer',
    companyName: 'Gujarat Chemical Corp',
    companyLogo: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Vadodara, Gujarat',
    state: 'Gujarat',
    district: 'Vadodara',
    city: 'Vadodara',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 1000000,
    maxSalary: 1600000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 15,
    description: 'Perform HAZOP risk analysis, chemical reactor safety audits, and effluent plant operations in Vadodara.',
    responsibilities: ['Lead HAZOP studies for chemical plants', 'Ensure environmental safety compliance'],
    requirements: ['B.Tech Chemical Engineering'],
    benefits: ['₹10 - 16 LPA + Safety Bonus'],
    skills: ['Chemical Engineering', 'HAZOP', 'Process Safety'],
    applyLink: 'https://gujaratchemical.com/jobs/process-safety',
    createdAt: new Date('2026-02-12T16:00:00Z')
  },
  {
    _id: 'j28',
    title: 'Solar Power Plant Site Engineer',
    companyName: 'CleanEnergy India Ltd',
    companyLogo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=150&auto=format&fit=crop&q=80',
    category: 'Engineering & Manufacturing',
    location: 'Jaipur, Rajasthan',
    state: 'Rajasthan',
    district: 'Jaipur City',
    city: 'Jaipur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 450000,
    maxSalary: 750000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 330,
    applicantsCount: 19,
    description: 'Commission 50MW utility solar grid installations, PV panel mounting, and central inverter wiring near Jaipur.',
    responsibilities: ['Supervise solar array structural installation', 'Commission solar grid inverters'],
    requirements: ['B.Tech / Diploma EEE'],
    benefits: ['₹4.5 - 7.5 LPA + Site Allowance'],
    skills: ['Solar PV', 'Electrical', 'Renewable Energy', 'Site Engineering'],
    applyLink: 'https://cleanenergy.in/careers/solar-site-eng',
    createdAt: new Date('2026-02-16T10:00:00Z')
  },

  // 4. Customer Service & BPO (8)
  {
    _id: 'j29',
    title: 'Customer Service & Helpdesk Specialist',
    companyName: 'TechConnect Customer Care',
    companyLogo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 18000,
    maxSalary: 32000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 710,
    applicantsCount: 64,
    description: 'Hiring 50 Customer Support Executives in Bhubaneswar for voice & email support desk operations.',
    responsibilities: ['Answer inbound customer phone calls', 'Log support tickets'],
    requirements: ['10+2 / Graduate with English & Odia fluency'],
    benefits: ['₹18,000 - ₹32,000 /month + Overtime'],
    skills: ['Customer Support', 'Communication', 'CRM', 'Helpdesk'],
    applyLink: 'https://techconnect.co.in/careers/bpo-exec',
    createdAt: new Date('2026-02-22T08:30:00Z')
  },
  {
    _id: 'j30',
    title: 'Human Resources Generalist',
    companyName: 'Kalinga HR & Talent Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Sambalpur, Sambalpur, Odisha',
    state: 'Odisha',
    district: 'Sambalpur',
    city: 'Sambalpur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 22000,
    maxSalary: 38000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 21,
    description: 'Handle employee onboarding, attendance payroll processing, and talent acquisition in Sambalpur office.',
    responsibilities: ['Conduct candidate interviews', 'Manage monthly payroll'],
    requirements: ['MBA HR / BBA Graduate'],
    benefits: ['₹22,000 - ₹38,000 /month'],
    skills: ['Recruitment', 'Payroll', 'Employee Relations', 'HR Ops'],
    applyLink: 'https://kalingahr.co.in/jobs/hr-generalist',
    createdAt: new Date('2026-02-17T14:00:00Z')
  },
  {
    _id: 'j31',
    title: 'Inbound Voice Support Executive',
    companyName: 'Apex Global BPO',
    companyLogo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Kolkata, West Bengal',
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 16000,
    maxSalary: 28000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 450,
    applicantsCount: 38,
    description: 'Provide customer query resolution in English & Bengali for telecom & banking clients in Salt Lake Sector V, Kolkata.',
    responsibilities: ['Handle inbound customer calls', 'Update CRM ticket logs'],
    requirements: ['Higher Secondary / Graduate'],
    benefits: ['₹16,000 - ₹28,000 /month + Cab Facility'],
    skills: ['Voice Process', 'Customer Care', 'Communication'],
    applyLink: 'https://apexbpo.in/careers/kolkata-voice',
    createdAt: new Date('2026-02-19T11:30:00Z')
  },
  {
    _id: 'j32',
    title: 'Technical Support Desk Engineer',
    companyName: 'TechConnect Care',
    companyLogo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Mohali, SAS Nagar, Punjab',
    state: 'Punjab',
    district: 'SAS Nagar (Mohali)',
    city: 'Mohali',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 24000,
    maxSalary: 42000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 380,
    applicantsCount: 27,
    description: 'Provide L1/L2 technical support for US hardware & internet routers in IT Park, Mohali.',
    responsibilities: ['Troubleshoot network connectivity issues', 'Guide users on software setup'],
    requirements: ['BCA / B.Sc IT / Any Graduate with tech knowledge'],
    benefits: ['₹24,000 - ₹42,000 /month + Night Allowance'],
    skills: ['Technical Support', 'Networking', 'Troubleshooting'],
    applyLink: 'https://techconnect.co.in/careers/tech-desk-mohali',
    createdAt: new Date('2026-02-18T16:00:00Z')
  },
  {
    _id: 'j33',
    title: 'Business Operations Associate',
    companyName: 'GrowthPulse India',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Gurugram, Haryana',
    state: 'Haryana',
    district: 'Gurugram',
    city: 'Gurugram',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 28000,
    maxSalary: 48000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 360,
    applicantsCount: 29,
    description: 'Manage daily client onboarding, vendor relations, and operational reports in Cyber City, Gurugram.',
    responsibilities: ['Assist operations team with client onboarding', 'Prepare weekly Excel reports'],
    requirements: ['Graduate degree with MS Excel skills'],
    benefits: ['₹28,000 - ₹48,000 /month'],
    skills: ['Operations', 'MS Excel', 'Communication'],
    applyLink: 'https://growthpulse.in/jobs/ops-associate',
    createdAt: new Date('2026-02-16T13:00:00Z')
  },
  {
    _id: 'j34',
    title: 'Client Onboarding Account Executive',
    companyName: 'BPO Global Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Patna, Bihar',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 20000,
    maxSalary: 35000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 310,
    applicantsCount: 23,
    description: 'Coordinate enterprise customer account setup, KYC verification, and contract signatures in Patna.',
    responsibilities: ['Verify customer KYC documents', 'Assist client onboarding queries'],
    requirements: ['Graduate in Any Stream'],
    benefits: ['₹20,000 - ₹35,000 /month'],
    skills: ['Client Onboarding', 'KYC', 'Customer Relationship'],
    applyLink: 'https://bpoglobal.in/jobs/patna-exec',
    createdAt: new Date('2026-02-15T10:00:00Z')
  },
  {
    _id: 'j35',
    title: 'International Voice Process Lead',
    companyName: 'Apex Global BPO',
    companyLogo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Noida, Gautam Buddha Nagar, Uttar Pradesh',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar (Noida)',
    city: 'Noida',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 35000,
    maxSalary: 65000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 440,
    applicantsCount: 35,
    description: 'Manage US healthcare & financial voice process teams in Sector 63, Noida. Monitor call quality metrics.',
    responsibilities: ['Supervise 15 voice support agents', 'Conduct call audits and SLA reviews'],
    requirements: ['2+ years international BPO experience'],
    benefits: ['₹35,000 - ₹65,000 /month + Both Side Cab'],
    skills: ['Voice Process', 'Quality Audit', 'Team Management'],
    applyLink: 'https://apexbpo.in/careers/noida-lead',
    createdAt: new Date('2026-02-21T15:00:00Z')
  },
  {
    _id: 'j36',
    title: 'Customer Success Manager (SaaS Desk)',
    companyName: 'SaaS Desk Systems',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    category: 'Customer Service & BPO',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 800000,
    maxSalary: 1300000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 390,
    applicantsCount: 26,
    description: 'Drive customer retention, product adoption, and ARR expansion for B2B SaaS clients in Koramangala, Bengaluru.',
    responsibilities: ['Conduct monthly customer health checks', 'Reduce churn and drive product adoption'],
    requirements: ['2+ years SaaS customer success experience'],
    benefits: ['₹8 - 13 LPA + Bonus'],
    skills: ['Customer Success', 'SaaS', 'Account Management'],
    applyLink: 'https://saasdesk.com/careers/csm',
    createdAt: new Date('2026-02-19T13:00:00Z')
  },

  // 5. Finance & Banking (7)
  {
    _id: 'j37',
    title: 'Financial Data Analyst',
    companyName: 'FinGlobal Systems',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Mumbai, Mumbai City, Maharashtra',
    state: 'Maharashtra',
    district: 'Mumbai City',
    city: 'Mumbai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 800000,
    maxSalary: 1400000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 420,
    applicantsCount: 28,
    description: 'Analyze financial markets, portfolio metrics, and risk management models in BKC, Mumbai.',
    responsibilities: ['Build financial dashboards in PowerBI', 'Analyze quarterly P&L'],
    requirements: ['MBA Finance / CFA with SQL'],
    benefits: ['₹8 - 14 LPA + Annual Bonus'],
    skills: ['Financial Analysis', 'SQL', 'Python', 'PowerBI'],
    applyLink: 'https://finglobal.com/careers/data-analyst',
    createdAt: new Date('2026-02-18T15:00:00Z')
  },
  {
    _id: 'j38',
    title: 'Commercial Branch Credit Manager',
    companyName: 'HDFC Retail Banking',
    companyLogo: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Lucknow, Uttar Pradesh',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 900000,
    maxSalary: 1500000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 380,
    applicantsCount: 22,
    description: 'Appraise SME loan applications, credit risk profiles, and financial balance sheets in Hazratganj branch, Lucknow.',
    responsibilities: ['Assess SME loan proposal credit risk', 'Conduct client financial audit'],
    requirements: ['CA / MBA Finance + 3 years credit underwriting'],
    benefits: ['₹9 - 15 LPA + Bank Benefits'],
    skills: ['Credit Assessment', 'Underwriting', 'Banking', 'Financial Analysis'],
    applyLink: 'https://hdfc.com/jobs/credit-manager-lucknow',
    createdAt: new Date('2026-02-17T11:00:00Z')
  },
  {
    _id: 'j39',
    title: 'Chartered Accountant & Tax Lead',
    companyName: 'Utkal Financial Services',
    companyLogo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 850000,
    maxSalary: 1450000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 340,
    applicantsCount: 19,
    description: 'Manage corporate GST filings, statutory audit compliance, and IT returns for corporate clients in Bhubaneswar.',
    responsibilities: ['File corporate GST & Income Tax returns', 'Conduct statutory internal audits'],
    requirements: ['ICAI Chartered Accountant (CA) qualification'],
    benefits: ['₹8.5 - 14.5 LPA'],
    skills: ['GST', 'Income Tax', 'Audit', 'Chartered Accountant', 'Tally'],
    applyLink: 'https://utkalfinance.co.in/careers/ca-lead',
    createdAt: new Date('2026-02-16T14:30:00Z')
  },
  {
    _id: 'j40',
    title: 'Investment Banking Analyst',
    companyName: 'Capital Edge Partners',
    companyLogo: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Mumbai, Mumbai City, Maharashtra',
    state: 'Maharashtra',
    district: 'Mumbai City',
    city: 'Mumbai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1400000,
    maxSalary: 2400000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 520,
    applicantsCount: 37,
    description: 'Prepare M&A valuation models, pitch books, and equity research decks in Lower Parel, Mumbai.',
    responsibilities: ['Build DCF & LBO financial valuation models', 'Draft client M&A pitch books'],
    requirements: ['MBA Finance / CA / CFA Level 2+'],
    benefits: ['₹14 - 24 LPA + Deal Performance Bonus'],
    skills: ['M&A', 'Valuation', 'Financial Modeling', 'Equity Research'],
    applyLink: 'https://capitaledge.in/careers/ib-analyst',
    createdAt: new Date('2026-02-21T12:00:00Z')
  },
  {
    _id: 'j41',
    title: 'Accounts Executive & Tally Specialist',
    companyName: 'Odisha Business Corp',
    companyLogo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Cuttack, Cuttack, Odisha',
    state: 'Odisha',
    district: 'Cuttack',
    city: 'Cuttack',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 18000,
    maxSalary: 30000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 300,
    applicantsCount: 25,
    description: 'Maintain daily vouchers, vendor payments, bank reconciliation, and Tally Prime entries in Cuttack.',
    responsibilities: ['Record daily receipts and payment vouchers in Tally', 'Reconcile monthly bank statements'],
    requirements: ['B.Com Graduate with Tally certification'],
    benefits: ['₹18,000 - ₹30,000 /month'],
    skills: ['Tally Prime', 'Accounting', 'GST Filing', 'Bookkeeping'],
    applyLink: 'https://odishabusiness.co.in/jobs/accounts-exec',
    createdAt: new Date('2026-02-14T09:00:00Z')
  },
  {
    _id: 'j42',
    title: 'Risk Management & Compliance Auditor',
    companyName: 'FinGlobal Systems',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Ahmedabad, Gujarat',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 750000,
    maxSalary: 1250000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 260,
    applicantsCount: 16,
    description: 'Ensure RBI regulatory compliance, internal financial risk audits, and anti-money laundering (AML) checks in Ahmedabad.',
    responsibilities: ['Audit internal financial risk controls', 'Ensure compliance with RBI & SEBI norms'],
    requirements: ['M.Com / CA Inter / MBA Finance'],
    benefits: ['₹7.5 - 12.5 LPA'],
    skills: ['Risk Audit', 'Compliance', 'AML', 'Financial Control'],
    applyLink: 'https://finglobal.com/careers/risk-auditor',
    createdAt: new Date('2026-02-13T15:00:00Z')
  },
  {
    _id: 'j43',
    title: 'Insurance Sales & Wealth Manager',
    companyName: 'LifeTrust Finance',
    companyLogo: 'https://images.unsplash.com/photo-1560520031-3a4dc4e9de0c?w=150&auto=format&fit=crop&q=80',
    category: 'Finance & Banking',
    location: 'Visakhapatnam, Andhra Pradesh',
    state: 'Andhra Pradesh',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 25000,
    maxSalary: 45000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 270,
    applicantsCount: 22,
    description: 'Advise high net-worth clients on life insurance, mutual fund portfolios, and retirement planning in Vizag.',
    responsibilities: ['Present wealth management investment solutions', 'Meet monthly sales targets'],
    requirements: ['Graduate degree with sales drive'],
    benefits: ['₹25,000 - ₹45,000 /month + Incentive Bonus'],
    skills: ['Insurance', 'Mutual Funds', 'Wealth Management', 'Sales'],
    applyLink: 'https://lifetrust.in/jobs/wealth-mgr-vizag',
    createdAt: new Date('2026-02-12T11:00:00Z')
  },

  // 6. Marketing & Digital (6)
  {
    _id: 'j44',
    title: 'UI/UX Product Designer',
    companyName: 'DesignVerse Studio',
    companyLogo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 750000,
    maxSalary: 1300000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 390,
    applicantsCount: 31,
    description: 'Create user journeys, wireframes, and design systems for web & mobile applications in Pune.',
    responsibilities: ['Design high fidelity Figma prototypes', 'Conduct user research'],
    requirements: ['2+ years UI/UX portfolio in Figma'],
    benefits: ['₹7.5 - 13 LPA + Ergonomic Desk Allowance'],
    skills: ['Figma', 'UI/UX', 'Wireframing', 'Prototyping'],
    applyLink: 'https://designverse.io/careers/uiux-designer',
    createdAt: new Date('2026-02-20T16:30:00Z')
  },
  {
    _id: 'j45',
    title: 'Digital Marketing & SEO Specialist',
    companyName: 'GrowthPulse India',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'Noida, Gautam Buddha Nagar, Uttar Pradesh',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar (Noida)',
    city: 'Noida',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 30000,
    maxSalary: 55000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 490,
    applicantsCount: 41,
    description: 'Lead Google Ads, Meta ad campaigns, organic SEO ranking, and content strategy in Sector 62, Noida.',
    responsibilities: ['Execute Google Pay-Per-Click campaigns', 'Perform SEO audits'],
    requirements: ['Digital Marketing Certification'],
    benefits: ['₹30,000 - ₹55,000 /month + Campaign Bonus'],
    skills: ['SEO', 'Google Ads', 'Meta Ads', 'Analytics'],
    applyLink: 'https://growthpulse.in/jobs/seo-specialist',
    createdAt: new Date('2026-02-14T10:00:00Z')
  },
  {
    _id: 'j46',
    title: 'E-Commerce Content Writer',
    companyName: 'TechMedia India',
    companyLogo: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'Kolkata, West Bengal',
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    workMode: 'Remote',
    jobType: 'Remote',
    experienceLevel: 'Entry Level',
    minSalary: 22000,
    maxSalary: 38000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 310,
    applicantsCount: 28,
    description: 'Write engaging SEO product descriptions, blog posts, and brand press releases for e-commerce brands.',
    responsibilities: ['Draft SEO blog articles & product copy', 'Edit marketing collateral'],
    requirements: ['Degree in English / Journalism / Mass Comms'],
    benefits: ['₹22,000 - ₹38,000 /month + 100% WFH'],
    skills: ['Content Writing', 'Copywriting', 'SEO', 'Blogging'],
    applyLink: 'https://techmedia.in/careers/content-writer',
    createdAt: new Date('2026-02-16T11:00:00Z')
  },
  {
    _id: 'j47',
    title: 'Brand Strategy & Performance Marketer',
    companyName: 'GrowthPulse India',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 1200000,
    maxSalary: 1900000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 480,
    applicantsCount: 33,
    description: 'Scale multi-crore digital ad spend across Meta, Google, LinkedIn, and influencer marketing channels.',
    responsibilities: ['Optimize user acquisition cost (CAC) and ROAS', 'Lead brand campaigns'],
    requirements: ['4+ years performance marketing experience'],
    benefits: ['₹12 - 19 LPA + Profit Share Bonus'],
    skills: ['Performance Marketing', 'ROAS', 'Brand Strategy', 'Google Ads'],
    applyLink: 'https://growthpulse.in/jobs/brand-lead',
    createdAt: new Date('2026-02-21T14:00:00Z')
  },
  {
    _id: 'j48',
    title: 'Video Editor & Motion Graphics Designer',
    companyName: 'MediaCraft Studio',
    companyLogo: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'Mumbai, Mumbai Suburban, Maharashtra',
    state: 'Maharashtra',
    district: 'Mumbai Suburban',
    city: 'Mumbai',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 28000,
    maxSalary: 50000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 340,
    applicantsCount: 27,
    description: 'Edit promotional brand reels, YouTube videos, 2D motion graphics, and ad creative clips in Andheri West.',
    responsibilities: ['Edit YouTube videos & Instagram reels in Premiere Pro', 'Design 2D motion graphics in After Effects'],
    requirements: ['Adobe Premiere Pro & After Effects portfolio'],
    benefits: ['₹28,000 - ₹50,000 /month'],
    skills: ['Premiere Pro', 'After Effects', 'Video Editing', 'Motion Graphics'],
    applyLink: 'https://mediacraft.in/careers/video-editor',
    createdAt: new Date('2026-02-18T12:00:00Z')
  },
  {
    _id: 'j49',
    title: 'Public Relations & Brand Communications Lead',
    companyName: 'CommsPulse India',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    category: 'Marketing & Digital',
    location: 'New Delhi, Delhi NCR',
    state: 'Delhi NCR',
    district: 'New Delhi',
    city: 'New Delhi',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 700000,
    maxSalary: 1150000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 18,
    description: 'Pitch media coverage to top print & digital news publications, draft press releases, and manage corporate PR.',
    responsibilities: ['Maintain relationships with media journalists', 'Draft press releases and executive speeches'],
    requirements: ['Degree in PR / Mass Communication'],
    benefits: ['₹7 - 11.5 LPA'],
    skills: ['PR', 'Public Relations', 'Media Pitching', 'Corporate Comms'],
    applyLink: 'https://commspulse.in/jobs/pr-lead',
    createdAt: new Date('2026-02-15T15:00:00Z')
  },

  // 7. Hospitality & Retail (6)
  {
    _id: 'j50',
    title: 'Retail Store & Sales Supervisor',
    companyName: 'Sun Retail & Lifestyle',
    companyLogo: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=150&auto=format&fit=crop&q=80',
    category: 'Hospitality & Retail',
    location: 'Puri, Puri, Odisha',
    state: 'Odisha',
    district: 'Puri',
    city: 'Puri',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 16000,
    maxSalary: 28000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 320,
    applicantsCount: 24,
    description: 'Manage flagship retail showroom in Puri town. Oversee billing counters, product merchandising, and inventory.',
    responsibilities: ['Maintain store stock register', 'Assist billing counter'],
    requirements: ['12th Pass / Diploma'],
    benefits: ['₹16,000 - ₹28,000 /month + Sales Incentives'],
    skills: ['Retail Sales', 'Billing', 'Customer Service'],
    applyLink: 'https://sunretail.in/jobs/puri-supervisor',
    createdAt: new Date('2026-02-19T14:15:00Z')
  },
  {
    _id: 'j51',
    title: 'Hotel Front Desk & Guest Relations Manager',
    companyName: 'Heritage Resorts India',
    companyLogo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=150&auto=format&fit=crop&q=80',
    category: 'Hospitality & Retail',
    location: 'Jaipur, Rajasthan',
    state: 'Rajasthan',
    district: 'Jaipur City',
    city: 'Jaipur',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 30000,
    maxSalary: 52000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 370,
    applicantsCount: 23,
    description: 'Oversee 5-star hotel front office check-in, VIP guest assistance, and room reservation software in Jaipur.',
    responsibilities: ['Supervise front desk staff', 'Manage Opera PMS reservation software'],
    requirements: ['BHM (Bachelor of Hotel Management)'],
    benefits: ['₹30,000 - ₹52,000 /month + Duty Meals & Stay'],
    skills: ['Front Office', 'Hotel Management', 'Guest Relations', 'Opera PMS'],
    applyLink: 'https://heritageresorts.in/careers/front-office-mgr',
    createdAt: new Date('2026-02-18T10:00:00Z')
  },
  {
    _id: 'j52',
    title: 'Restaurant Operations & F&B Manager',
    companyName: 'Coastal Hospitality Group',
    companyLogo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=150&auto=format&fit=crop&q=80',
    category: 'Hospitality & Retail',
    location: 'Panaji, North Goa, Goa',
    state: 'Goa',
    district: 'North Goa (Panaji)',
    city: 'Panaji',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Senior Level',
    minSalary: 45000,
    maxSalary: 75000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 410,
    applicantsCount: 26,
    description: 'Manage high-volume beachfront fine dining restaurant, food safety standards, bar inventory, and staffing in Panaji.',
    responsibilities: ['Supervise F&B service staff & kitchen team', 'Manage daily bar stock inventory'],
    requirements: ['Degree in Hotel & Restaurant Management'],
    benefits: ['₹45,000 - ₹75,000 /month + Tips Share'],
    skills: ['F&B Management', 'Restaurant Ops', 'Food Safety', 'Hospitality'],
    applyLink: 'https://coastalgroup.in/jobs/fb-manager',
    createdAt: new Date('2026-02-17T17:00:00Z')
  },
  {
    _id: 'j53',
    title: 'Supermarket Store Inventory Manager',
    companyName: 'Reliance Fresh Mart',
    companyLogo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=150&auto=format&fit=crop&q=80',
    category: 'Hospitality & Retail',
    location: 'Rourkela, Sundargarh, Odisha',
    state: 'Odisha',
    district: 'Sundargarh (Rourkela HQ)',
    city: 'Rourkela',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 20000,
    maxSalary: 34000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 260,
    applicantsCount: 19,
    description: 'Oversee daily grocery stock receiving, expiry audits, billing POS counters, and retail staff in Rourkela.',
    responsibilities: ['Audit daily shelf stock & fresh produce', 'Manage retail POS billing team'],
    requirements: ['Graduate in Any Stream'],
    benefits: ['₹20,000 - ₹34,000 /month'],
    skills: ['Retail Inventory', 'Supermarket', 'POS Billing', 'Stock Audit'],
    applyLink: 'https://reliancefresh.in/careers/rourkela-mgr',
    createdAt: new Date('2026-02-15T09:30:00Z')
  },
  {
    _id: 'j54',
    title: 'E-Commerce Warehouse Dispatch Supervisor',
    companyName: 'Express Retail Logistics',
    companyLogo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    category: 'Hospitality & Retail',
    location: 'Surat, Gujarat',
    state: 'Gujarat',
    district: 'Surat',
    city: 'Surat',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 22000,
    maxSalary: 38000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 290,
    applicantsCount: 22,
    description: 'Supervise order packing, barcode scanning, and last-mile courier dispatch in Surat fulfillment warehouse.',
    responsibilities: ['Supervise package picking & barcode scans', 'Dispatch daily courier shipments'],
    requirements: ['10+2 / Diploma with basic computer knowledge'],
    benefits: ['₹22,000 - ₹38,000 /month + Night Allowance'],
    skills: ['Warehouse', 'Dispatch', 'Logistics', 'Inventory'],
    applyLink: 'https://expressretail.in/jobs/surat-warehouse',
    createdAt: new Date('2026-02-13T11:00:00Z')
  },
  {
    _id: 'j55',
    title: 'Luxury Boutique Store Manager',
    companyName: 'Lifestyle Brands India',
    companyLogo: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=150&auto=format&fit=crop&q=80',
    category: 'Hospitality & Retail',
    location: 'New Delhi, Delhi NCR',
    state: 'Delhi NCR',
    district: 'New Delhi',
    city: 'New Delhi',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 40000,
    maxSalary: 70000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 350,
    applicantsCount: 24,
    description: 'Lead high-end apparel luxury boutique showroom operations, clienteling, and VIP sales in Khan Market, New Delhi.',
    responsibilities: ['Deliver luxury clienteling customer service', 'Manage store P&L and sales target'],
    requirements: ['2+ years luxury retail management experience'],
    benefits: ['₹40,000 - ₹70,000 /month + Commission'],
    skills: ['Luxury Retail', 'Store Management', 'Visual Merchandising'],
    applyLink: 'https://lifestylebrands.in/careers/boutique-mgr',
    createdAt: new Date('2026-02-21T11:30:00Z')
  }
];

const seedDatabaseIfEmpty = async () => {
  try {
    const isMongoConnected = require('mongoose').connection.readyState === 1;

    if (isMongoConnected) {
      const count = await Job.countDocuments();
      if (count < 50) {
        console.log(`Seeding MongoDB "jobs" collection with ${UNIQUE_55_JOBS.length} unique sample records...`);
        await Job.deleteMany({}); // Ensure clean unique dataset
        const formattedJobs = UNIQUE_55_JOBS.map(j => {
          const { _id, ...rest } = j;
          return rest;
        });
        await Job.insertMany(formattedJobs);
        console.log(`Successfully inserted ${UNIQUE_55_JOBS.length} unique job records into MongoDB!`);
      } else {
        console.log(`MongoDB "jobs" collection contains ${count} unique records.`);
      }
    }

    // Always update in-memory store as well for instant fallback
    memoryStore.jobs = [...UNIQUE_55_JOBS];
    console.log(`In-memory store updated with ${memoryStore.jobs.length} unique jobs.`);
  } catch (err) {
    console.error('Error seeding database jobs:', err.message);
  }
};

module.exports = { UNIQUE_55_JOBS, seedDatabaseIfEmpty };
