const Job = require('../models/Job');
const { memoryStore } = require('./db');

const UNIQUE_60_JOBS = [
  // ================= GOVERNMENT JOBS (SARKARI NAUKRI & PSUs) =================
  {
    _id: 'g1',
    title: 'OSSC Junior Executive Assistant Recruitment',
    companyName: 'Odisha Staff Selection Commission (OSSC)',
    companyLogo: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Odisha State Govt (OSSC)',
    officialAdvtNo: 'Advt. No. OSSC/3840/2026',
    category: 'Government & Public Sector',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Freshers Eligible',
    minSalary: 35400,
    maxSalary: 112400,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 1420,
    applicantsCount: 185,
    description: 'Government of Odisha invites online applications for 250 posts of Junior Executive Assistant in State Secretariat departments. Pay Level 9 of ORSP Rules.',
    responsibilities: ['Assist senior officers in file processing and administrative records', 'Draft official correspondence and digital file tracking'],
    requirements: ['Bachelor Degree in Any Discipline from a Recognized University', 'Basic Computer Skills (ODIA & English typing)'],
    benefits: ['Pay Level 9 (₹35,400 - ₹1,12,400 /month)', 'Government Pension & Family Medical Cover', 'DA, HRA & Special Allowance'],
    skills: ['Administration', 'Drafting', 'Computer Typing', 'MS Office', 'Odia'],
    applyLink: 'https://www.ossc.gov.in',
    lastDateToApply: new Date('2026-03-31'),
    createdAt: new Date('2026-02-25T08:00:00Z')
  },
  {
    _id: 'g2',
    title: 'OPSC Assistant Section Officer (ASO)',
    companyName: 'Odisha Public Service Commission (OPSC)',
    companyLogo: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Odisha Public Service Commission',
    officialAdvtNo: 'Advt. No. 12 of 2026-27',
    category: 'Government & Public Sector',
    location: 'Cuttack, Cuttack, Odisha',
    state: 'Odisha',
    district: 'Cuttack',
    city: 'Cuttack',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Freshers Eligible',
    minSalary: 44900,
    maxSalary: 142400,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 1890,
    applicantsCount: 240,
    description: 'OPSC invites online recruitment applications for Group B Assistant Section Officers in Odisha Governor Secretariat and State Departments.',
    responsibilities: ['Manage policy file scrutiny and departmental executive files', 'Coordinate inter-departmental notifications'],
    requirements: ['Graduate Degree in Any Stream', 'Age: 21 to 38 Years (Relaxation as per Odisha Govt Rules)'],
    benefits: ['Pay Level 10 (₹44,900 - ₹1,42,400 /month)', 'Government Quarters Facility in Cuttack/Bhubaneswar'],
    skills: ['General Knowledge', 'English Drafting', 'Reasoning', 'Mathematics'],
    applyLink: 'https://www.opsc.gov.in',
    lastDateToApply: new Date('2026-04-15'),
    createdAt: new Date('2026-02-26T09:30:00Z')
  },
  {
    _id: 'g3',
    title: 'SBI Probationary Officer (PO) Recruitment 2026',
    companyName: 'State Bank of India (SBI)',
    companyLogo: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Public Sector Bank (SBI)',
    officialAdvtNo: 'CRPD/PO/2026-27/01',
    category: 'Finance & Banking',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Freshers Eligible',
    minSalary: 65000,
    maxSalary: 95000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 2150,
    applicantsCount: 310,
    description: 'State Bank of India invites applications for 2,000 Probationary Officer posts across SBI Circles nationwide including Odisha Circle.',
    responsibilities: ['Branch banking operations, credit processing, and customer relationship management', 'Manage retail loan appraisals and NPA recovery'],
    requirements: ['Graduation in any discipline from a recognized University'],
    benefits: ['₹65,000 - ₹95,000 /month Starting Pay + Leased Accommodation', 'LTC, Medical Cover, Bank Concessional Loans'],
    skills: ['Banking Operations', 'Credit Appraisal', 'Financial Analysis', 'Quantitative Aptitude'],
    applyLink: 'https://bank.sbi/careers',
    lastDateToApply: new Date('2026-03-25'),
    createdAt: new Date('2026-02-24T10:00:00Z')
  },
  {
    _id: 'g4',
    title: 'RRB Junior Engineer (JE) Railway Recruitment',
    companyName: 'Railway Recruitment Board (RRB)',
    companyLogo: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Indian Railways (Ministry of Railways)',
    officialAdvtNo: 'CEN 03/2026 (RRB-JE)',
    category: 'Government & Public Sector',
    location: 'Rourkela, Sundargarh, Odisha',
    state: 'Odisha',
    district: 'Sundargarh (Rourkela HQ)',
    city: 'Rourkela',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Freshers Eligible',
    minSalary: 35400,
    maxSalary: 112400,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 1680,
    applicantsCount: 205,
    description: 'Indian Railways RRB invites applications for 7,500 Junior Engineer (Civil, Electrical, Mechanical, Signal & Telecom) posts.',
    responsibilities: ['Oversee railway track maintenance, signalling equipment, and locomotive workshops', 'Supervise railway civil engineering works'],
    requirements: ['Diploma / B.Tech in Civil, Electrical, Mechanical, or Electronics Engineering'],
    benefits: ['Pay Level 6 + Railway Free Pass + Medical Cover for Family'],
    skills: ['Railway Engineering', 'Civil', 'Electrical', 'Mechanical', 'Technical CBT'],
    applyLink: 'https://rrbcdg.gov.in',
    lastDateToApply: new Date('2026-04-10'),
    createdAt: new Date('2026-02-22T11:00:00Z')
  },
  {
    _id: 'g5',
    title: 'NALCO Graduate Engineer Trainee (GET)',
    companyName: 'National Aluminium Company Ltd (NALCO)',
    companyLogo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Central Navratna PSU (Ministry of Mines)',
    officialAdvtNo: 'Advt. No. 1026/GET/2026',
    category: 'Engineering & Manufacturing',
    location: 'Angul, Angul, Odisha',
    state: 'Odisha',
    district: 'Angul',
    city: 'Angul',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Freshers Eligible',
    minSalary: 600000,
    maxSalary: 1800000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 1350,
    applicantsCount: 165,
    description: 'NALCO, a Navratna Central PSU, requires Graduate Engineer Trainees in Mechanical, Electrical, Metallurgy, Chemical, and Mining disciplines.',
    responsibilities: ['Undergo 1-year intensive GET training at NALCO Smelter & Power Plant Angul', 'Assist in plant engineering and production ops'],
    requirements: ['B.Tech / B.E. with GATE 2026 Score in relevant branch'],
    benefits: ['₹6 - 18 LPA (E-1 Grade on confirmation) + PSU Township Accommodation'],
    skills: ['Metallurgy', 'Mechanical', 'Electrical', 'GATE Score', 'Plant Ops'],
    applyLink: 'https://www.nalcoindia.com/careers',
    lastDateToApply: new Date('2026-03-30'),
    createdAt: new Date('2026-02-23T14:00:00Z')
  },
  {
    _id: 'g6',
    title: 'SAIL Management Trainee (Technical)',
    companyName: 'Steel Authority of India Ltd (SAIL)',
    companyLogo: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Central Maharatna PSU (Ministry of Steel)',
    officialAdvtNo: 'Pers/RSP/MT(T)/2026',
    category: 'Engineering & Manufacturing',
    location: 'Rourkela, Sundargarh, Odisha',
    state: 'Odisha',
    district: 'Sundargarh (Rourkela HQ)',
    city: 'Rourkela',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Freshers Eligible',
    minSalary: 500000,
    maxSalary: 1600000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: false,
    status: 'Active',
    viewsCount: 1220,
    applicantsCount: 145,
    description: 'SAIL Rourkela Steel Plant invites applications for Management Trainee (Technical) in Metallurgy, Mechanical, Electrical, and Civil branches.',
    responsibilities: ['Supervise blast furnace operations, rolling mills, and quality testing in Rourkela Steel Plant'],
    requirements: ['B.Tech / B.E. Degree with minimum 65% marks'],
    benefits: ['₹5 - 16 LPA + SAIL Steel Township Accommodation'],
    skills: ['Steel Manufacturing', 'Metallurgy', 'Mechanical', 'Electrical'],
    applyLink: 'https://sail.co.in/careers',
    lastDateToApply: new Date('2026-04-05'),
    createdAt: new Date('2026-02-21T09:00:00Z')
  },
  {
    _id: 'g7',
    title: 'ISRO Scientist / Engineer SC Recruitment',
    companyName: 'Indian Space Research Organisation (ISRO)',
    companyLogo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Department of Space (Govt of India)',
    officialAdvtNo: 'ICRB:02:2026',
    category: 'Government & Public Sector',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Freshers Eligible',
    minSalary: 56100,
    maxSalary: 177500,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 2450,
    applicantsCount: 380,
    description: 'ISRO Centralised Recruitment Board (ICRB) invites applications for Scientist/Engineer SC (Electronics, Mechanical, Computer Science).',
    responsibilities: ['Design space payload systems, satellite launch vehicle avionics, and satellite mission control algorithms'],
    requirements: ['B.Tech / B.E. First Class with aggregate 65% marks'],
    benefits: ['Pay Level 10 (₹56,100 - ₹1,77,500 /month) + ISRO Quarters + Performance Allowance'],
    skills: ['Space Systems', 'Avionics', 'Electronics', 'Computer Science', 'Rocketry'],
    applyLink: 'https://www.isro.gov.in/careers',
    lastDateToApply: new Date('2026-04-20'),
    createdAt: new Date('2026-02-27T10:00:00Z')
  },
  {
    _id: 'g8',
    title: 'AIIMS Senior Nursing Officer Recruitment',
    companyName: 'All India Institute of Medical Sciences (AIIMS)',
    companyLogo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=150&auto=format&fit=crop&q=80',
    sector: 'Government',
    govtDepartment: 'Ministry of Health & Family Welfare',
    officialAdvtNo: 'AIIMS/BBSR/SNO/2026/01',
    category: 'Healthcare & Medical',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Govt Regular',
    experienceLevel: 'Mid Level',
    minSalary: 47600,
    maxSalary: 151100,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 980,
    applicantsCount: 110,
    description: 'AIIMS Bhubaneswar invites online applications for Senior Nursing Officer (Staff Nurse Grade-I) in AIIMS Hospital complex.',
    responsibilities: ['Manage ICU and super-specialty ward nursing care', 'Supervise junior nursing staff and OT protocols'],
    requirements: ['B.Sc Nursing / Post Basic B.Sc Nursing with 3 years clinical experience'],
    benefits: ['Pay Level 8 (₹47,600 - ₹1,51,100 /month) + AIIMS Campus Housing'],
    skills: ['Critical Nursing', 'ICU', 'Patient Care', 'AIIMS Standards'],
    applyLink: 'https://aiimsbhubaneswar.nic.in',
    lastDateToApply: new Date('2026-03-28'),
    createdAt: new Date('2026-02-20T12:00:00Z')
  },

  // ================= PRIVATE SECTOR JOBS =================
  {
    _id: 'j1',
    title: 'Senior Full Stack Software Engineer',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    sector: 'Private',
    category: 'Technology & IT',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1000000,
    maxSalary: 1600000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 540,
    applicantsCount: 34,
    description: 'Join Infovalley IT Hub in Bhubaneswar! Apex Infotech is hiring Senior Full Stack React & Node.js Developers for enterprise cloud platforms.',
    responsibilities: ['Develop frontend React interfaces', 'Build Node.js microservices', 'Optimize MongoDB performance'],
    requirements: ['3+ years React & Node.js experience'],
    benefits: ['₹10 - 16 LPA Annual Package', 'Family Health Cover'],
    skills: ['React', 'Node.js', 'JavaScript', 'MongoDB', 'Express'],
    applyLink: 'https://apexinfotech.co.in/careers/fullstack-eng',
    createdAt: new Date('2026-02-20T08:00:00Z')
  },
  {
    _id: 'j2',
    title: 'Junior Web Developer Trainee',
    companyName: 'Apex Infotech India',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    sector: 'Private',
    category: 'Technology & IT',
    location: 'Cuttack, Cuttack, Odisha',
    state: 'Odisha',
    district: 'Cuttack',
    city: 'Cuttack',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 25000,
    maxSalary: 45000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 680,
    applicantsCount: 52,
    description: 'Great career start for fresh computer science graduates in Cuttack! Junior React frontend trainee position with structured mentoring.',
    responsibilities: ['Assist senior developers', 'Fix UI bugs', 'Build responsive layouts'],
    requirements: ['B.Tech / BCA with HTML, CSS, JavaScript'],
    benefits: ['₹25,000 - ₹45,000 /month stipend'],
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    applyLink: 'https://apexinfotech.co.in/careers/junior-dev',
    createdAt: new Date('2026-02-21T09:30:00Z')
  },
  {
    _id: 'j3',
    title: 'Frontend React Developer',
    companyName: 'CloudCraft Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    sector: 'Private',
    category: 'Technology & IT',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Hybrid',
    jobType: 'Full-time',
    experienceLevel: 'Mid Level',
    minSalary: 1200000,
    maxSalary: 1800000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 890,
    applicantsCount: 78,
    description: 'Building high scale SaaS applications in Indiranagar, Bengaluru. Looking for strong React, TypeScript, and Redux Engineers.',
    responsibilities: ['Develop SPA apps in React 18', 'Optimize Web Vitals'],
    requirements: ['3+ years React & TypeScript experience'],
    benefits: ['₹12 - 18 LPA + Stock Options'],
    skills: ['React', 'TypeScript', 'Redux', 'TailwindCSS'],
    applyLink: 'https://cloudcraft.dev/careers/react-eng',
    createdAt: new Date('2026-02-21T10:00:00Z')
  },
  {
    _id: 'j4',
    title: 'DevOps & Cloud Infrastructure Lead',
    companyName: 'CloudCraft Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    sector: 'Private',
    category: 'Technology & IT',
    location: 'Bengaluru, Bengaluru Urban, Karnataka',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    workMode: 'Remote',
    jobType: 'Remote',
    experienceLevel: 'Senior Level',
    minSalary: 1500000,
    maxSalary: 2400000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Yearly',
    featured: true,
    status: 'Active',
    viewsCount: 650,
    applicantsCount: 45,
    description: 'Remote AWS & Kubernetes DevOps role. Architect CI/CD pipelines, Docker containers, and infrastructure as code.',
    responsibilities: ['Manage AWS ECS, EKS, Terraform scripts', 'Ensure 99.99% uptime'],
    requirements: ['AWS Certified Solutions Architect + Docker/Kubernetes'],
    benefits: ['₹15 - 24 LPA + 100% Remote'],
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    applyLink: 'https://cloudcraft.dev/careers/devops-sr',
    createdAt: new Date('2026-02-22T11:00:00Z')
  },
  {
    _id: 'j5',
    title: 'Customer Service & Helpdesk Specialist',
    companyName: 'TechConnect Customer Care',
    companyLogo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    sector: 'Private',
    category: 'Customer Service & BPO',
    location: 'Bhubaneswar, Khordha, Odisha',
    state: 'Odisha',
    district: 'Khordha (Bhubaneswar HQ)',
    city: 'Bhubaneswar',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 18000,
    maxSalary: 32000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: true,
    status: 'Active',
    viewsCount: 710,
    applicantsCount: 64,
    description: 'Hiring 50 Customer Support Executives in Bhubaneswar for voice & email support desk operations.',
    responsibilities: ['Answer inbound customer phone calls', 'Log support tickets'],
    requirements: ['10+2 / Graduate with English & Odia fluency'],
    benefits: ['₹18,000 - ₹32,000 /month + Overtime'],
    skills: ['Customer Support', 'Communication', 'CRM', 'Helpdesk'],
    applyLink: 'https://techconnect.co.in/careers/bpo-exec',
    createdAt: new Date('2026-02-22T08:30:00Z')
  },
  {
    _id: 'j6',
    title: 'Retail Store & Sales Supervisor',
    companyName: 'Sun Retail & Lifestyle',
    companyLogo: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=150&auto=format&fit=crop&q=80',
    sector: 'Private',
    category: 'Hospitality & Retail',
    location: 'Puri, Puri, Odisha',
    state: 'Odisha',
    district: 'Puri',
    city: 'Puri',
    workMode: 'On-site',
    jobType: 'Full-time',
    experienceLevel: 'Entry Level',
    minSalary: 16000,
    maxSalary: 28000,
    salaryCurrency: 'INR',
    salaryPeriod: 'Monthly',
    featured: false,
    status: 'Active',
    viewsCount: 320,
    applicantsCount: 24,
    description: 'Manage flagship retail showroom in Puri town. Oversee billing counters, product merchandising, and inventory.',
    responsibilities: ['Maintain store stock register', 'Assist billing counter'],
    requirements: ['12th Pass / Diploma'],
    benefits: ['₹16,000 - ₹28,000 /month + Sales Incentives'],
    skills: ['Retail Sales', 'Billing', 'Customer Service'],
    applyLink: 'https://sunretail.in/jobs/puri-supervisor',
    createdAt: new Date('2026-02-19T14:15:00Z')
  }
];

const seedDatabaseIfEmpty = async () => {
  try {
    const isMongoConnected = require('mongoose').connection.readyState === 1;

    if (isMongoConnected) {
      const count = await Job.countDocuments();
      if (count < 50) {
        console.log(`Seeding MongoDB "jobs" collection with ${UNIQUE_60_JOBS.length} Government & Private sample records...`);
        await Job.deleteMany({}); // Ensure clean dataset
        const formattedJobs = UNIQUE_60_JOBS.map(j => {
          const { _id, ...rest } = j;
          return rest;
        });
        await Job.insertMany(formattedJobs);
        console.log(`Successfully inserted ${UNIQUE_60_JOBS.length} Government & Private job records into MongoDB!`);
      } else {
        console.log(`MongoDB "jobs" collection contains ${count} records.`);
      }
    }

    // Update in-memory store
    memoryStore.jobs = [...UNIQUE_60_JOBS];
    console.log(`In-memory store updated with ${memoryStore.jobs.length} Govt & Private jobs.`);
  } catch (err) {
    console.error('Error seeding database jobs:', err.message);
  }
};

module.exports = { UNIQUE_60_JOBS, seedDatabaseIfEmpty };
