import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' }
];

export const TRANSLATIONS = {
  en: {
    findJobs: 'Find Jobs',
    browseAll: 'Browse All',
    myApplications: 'My Applications',
    employerHub: 'Employer Hub',
    adminPanel: 'Admin Panel',
    signIn: 'Sign In',
    postFindJobs: 'Post / Find Jobs',
    heroTag: '#1 Pan India Job Portal',
    heroTitle: 'Find Your Dream Career Across Pan India',
    heroSubtitle: 'Discover thousands of verified opportunities across all 28 States, UTs & 30 Districts of Odisha.',
    searchPlaceholder: 'Job title, skills, keyword, or company...',
    locationPlaceholder: 'City, District, or State',
    stateDistrictBtn: 'State & District',
    searchBtn: 'Search Jobs',
    popularSearches: 'Popular Pan India Searches:',
    activeJobs: 'Active Pan India Jobs',
    verifiedEmployers: 'Verified Employers',
    successfulHires: 'Successful Hires',
    featuredOpenings: 'Featured Pan India Openings',
    quickView: 'Quick View',
    applyNow: 'Apply Now',
    aiAssistant: 'AI Assistant',
    selectLanguage: 'Select Language',

    // New Common Keys
    goalBtn: 'Goal: Job or Hire?',
    companyReviews: 'Company Reviews',
    sectorFilters: 'Sector & Filters',
    resetFilters: 'Reset',
    jobSector: 'Job Sector',
    allSectors: 'All Job Sectors',
    govtSarkari: 'Govt / Sarkari Naukri & PSUs',
    privateCompany: 'Private Company Openings',
    salaryRangeType: 'Salary Range Type',
    allPayRanges: 'All Pay Ranges (Thousands & Lakhs)',
    thousandsPerMonth: 'Thousands / Month (₹15k - ₹50k /mo)',
    lakhsPerAnnum: 'Lakhs Per Annum (₹6 - ₹30+ LPA)',
    selectStateUT: 'Select State / UT',
    allStatesUTs: 'All States & UTs',
    workLocationMode: 'Work Location Mode',
    anyMode: 'Any Mode',
    onSite: 'On-site',
    workFromHome: 'Work from Home (Remote)',
    hybrid: 'Hybrid',
    sortBy: 'Sort By:',
    mostRecent: 'Most Recent',
    highestSalary: 'Highest Salary',
    jobsFound: 'Jobs Found',
    showingOpenPositions: 'Showing open positions in',
    featured: 'Featured',
    govtBadge: 'Govt / Sarkari',
    govtRegular: 'Govt Regular',
    posted: 'Posted',
    applyBy: 'Apply by',
    officialApply: 'Official Apply',
    saveJob: 'Save Job',
    saved: 'Saved',

    // Modal & Pages
    whatIsYourGoal: 'What is your main goal today?',
    iWantJob: 'I Want a Job',
    iWantJobDesc: 'Find local & pan-India jobs, apply quickly',
    iWantHire: 'I Want to Hire People',
    iWantHireDesc: 'Post job openings, manage candidates',
    findGreatPlaces: 'Find Great Places to Work',
    getUnfilteredApp: 'Get unfiltered insights from current & former employees',
    searchCompanyPlaceholder: 'Search company name (e.g. ISRO, TCS, Tata Motors...)',
    ratings: 'Ratings',
    reviews: 'Reviews',
    salaries: 'Salaries',
    questions: 'Questions',
    openJobs: 'Open Jobs',
    footerDesc: "India's leading job portal for verified private and government jobs across 28 states & 30 districts of Odisha.",
    quickLinks: 'Quick Links',
    popularLocations: 'Popular Locations',
    contactSupport: 'Contact & Support',
    rightsReserved: 'All rights reserved.'
  },
  hi: {
    findJobs: 'नौकरी खोजें',
    browseAll: 'सभी देखें',
    myApplications: 'मेरे आवेदन',
    employerHub: 'नियोक्ता हब',
    adminPanel: 'एडमिन पैनल',
    signIn: 'साइन इन करें',
    postFindJobs: 'जॉब पोस्ट / खोजें',
    heroTag: '#1 ऑल इंडिया जॉब पोर्टल',
    heroTitle: 'पूरे भारत में अपना ड्रीम करियर खोजें',
    heroSubtitle: 'सभी 28 राज्यों, केंद्र शासित प्रदेशों और ओडिशा के 30 जिलों में हजारों सत्यापित अवसरों की खोज करें।',
    searchPlaceholder: 'नौकरी का शीर्षक, कौशल, या कंपनी...',
    locationPlaceholder: 'शहर, जिला, या राज्य',
    stateDistrictBtn: 'राज्य और जिला',
    searchBtn: 'नौकरी खोजें',
    popularSearches: 'लोकप्रिय खोजें:',
    activeJobs: 'सक्रिय भारत नौकरियां',
    verifiedEmployers: 'सत्यापित नियोक्ता',
    successfulHires: 'सफल भर्तियां',
    featuredOpenings: 'प्रमुख भारत नौकरियां',
    quickView: 'त्वरित देखें',
    applyNow: 'अभी आवेदन करें',
    aiAssistant: 'एआई सहायक',
    selectLanguage: 'भाषा चुनें',

    goalBtn: 'लक्ष्य: नौकरी या भर्ती?',
    companyReviews: 'कंपनी समीक्षाएं',
    sectorFilters: 'सेक्टर और फ़िल्टर',
    resetFilters: 'रीसेट',
    jobSector: 'नौकरी क्षेत्र',
    allSectors: 'सभी नौकरी क्षेत्र',
    govtSarkari: 'सरकारी नौकरी और पीएसयू',
    privateCompany: 'प्राइवेट कंपनी नौकरियां',
    salaryRangeType: 'वेतन सीमा प्रकार',
    allPayRanges: 'सभी वेतन सीमाएं (हजार और लाख)',
    thousandsPerMonth: 'हजार / माह (₹15k - ₹50k/माह)',
    lakhsPerAnnum: 'लाख प्रति वर्ष (₹6 - ₹30+ एलपीए)',
    selectStateUT: 'राज्य / केंद्र शासित प्रदेश चुनें',
    allStatesUTs: 'सभी राज्य और केंद्र शासित प्रदेश',
    workLocationMode: 'कार्य स्थान मोड',
    anyMode: 'कोई भी मोड',
    onSite: 'ऑन-साइट (ऑफिस)',
    workFromHome: 'वर्क फ्रॉम होम (रिमोट)',
    hybrid: 'हाइब्रिड',
    sortBy: 'क्रमबद्ध करें:',
    mostRecent: 'नवीनतम',
    highestSalary: 'उच्चतम वेतन',
    jobsFound: 'नौकरियां मिलीं',
    showingOpenPositions: 'में उपलब्ध नौकरियां देखी जा रही हैं',
    featured: 'प्रमुख',
    govtBadge: 'सरकारी',
    govtRegular: 'सरकारी नियमित',
    posted: 'पोस्ट तिथि',
    applyBy: 'अंतिम तिथि',
    officialApply: 'आधिकारिक आवेदन',
    saveJob: 'सेव करें',
    saved: 'सेव्ड',

    whatIsYourGoal: 'आज आपका मुख्य लक्ष्य क्या है?',
    iWantJob: 'मुझे नौकरी चाहिए',
    iWantJobDesc: 'स्थानीय और ऑल इंडिया नौकरियां खोजें, तुरंत आवेदन करें',
    iWantHire: 'मुझे लोग हायर करने हैं',
    iWantHireDesc: 'नौकरी पोस्ट करें, उम्मीदवारों को प्रबंधित करें',
    findGreatPlaces: 'सर्वश्रेष्ठ कार्यस्थलों की समीक्षाएं खोजें',
    getUnfilteredApp: 'कर्मचारियों की समीक्षाएं और वेतन जानकारी देखें',
    searchCompanyPlaceholder: 'कंपनी का नाम खोजें (जैसे ISRO, TCS, Tata...)',
    ratings: 'रेटिंग',
    reviews: 'समीक्षाएं',
    salaries: 'वेतन',
    questions: 'प्रश्न',
    openJobs: 'उपलब्ध नौकरियां',
    footerDesc: 'भारत के 28 राज्यों और ओडिशा के 30 जिलों के लिए प्रमुख नौकरी पोर्टल।',
    quickLinks: 'त्वरित लिंक',
    popularLocations: 'लोकप्रिय स्थान',
    contactSupport: 'संपर्क और सहायता',
    rightsReserved: 'सर्वाधिकार सुरक्षित।'
  },
  or: {
    findJobs: 'ଚାକିରି ଖୋଜନ୍ତୁ',
    browseAll: 'ସମସ୍ତ ଦେଖନ୍ତୁ',
    myApplications: 'ମୋର ଆବେଦନ',
    employerHub: 'ନିଯୁକ୍ତିଦାତା ହବ୍',
    adminPanel: 'ଆଡମିନ୍ ପ୍ୟାନେଲ୍',
    signIn: 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    postFindJobs: 'ପୋଷ୍ଟ / ଖୋଜନ୍ତୁ',
    heroTag: '#1 ସମଗ୍ର ଭାରତ ଓ ଓଡ଼ିଶା ଚାକିରି ପୋର୍ଟାଲ୍',
    heroTitle: 'ଓଡ଼ିଶା ଓ ସମଗ୍ର ଭାରତରେ ଆପଣଙ୍କ ସ୍ୱପ୍ନର ଚାକିରି ଖୋଜନ୍ତୁ',
    heroSubtitle: 'ଓଡ଼ିଶାର ସମସ୍ତ ୩୦ ଜିଲ୍ଲା ଏବଂ ଭାରତର ୨୮ ରାଜ୍ୟରେ ହଜାର ହଜାର ଚାକିରି ସୁଯୋଗ।',
    searchPlaceholder: 'ଚାକିରି ନାମ, ଦକ୍ଷତା, କିମ୍ବା କମ୍ପାନୀ...',
    locationPlaceholder: 'ସହର, ଜିଲ୍ଲା, କିମ୍ବା ରାଜ୍ୟ',
    stateDistrictBtn: 'ରାଜ୍ୟ ଓ ଜିଲ୍ଲା',
    searchBtn: 'ଚାକିରି ଖୋଜନ୍ତୁ',
    popularSearches: 'ଲୋକପ୍ରିୟ ଖୋଜ:',
    activeJobs: 'ସକ୍ରିୟ ଚାକିରି',
    verifiedEmployers: 'ଯାଞ୍ଚ ହୋଇଥିବା କମ୍ପାନୀ',
    successfulHires: 'ସଫଳ ନିଯୁକ୍ତି',
    featuredOpenings: 'ପ୍ରମୁଖ ଚାକିରି',
    quickView: 'ଶୀଘ୍ର ଦେଖନ୍ତୁ',
    applyNow: 'ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ',
    aiAssistant: 'ଏଆଇ ସହାୟକ',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',

    goalBtn: 'ଲକ୍ଷ୍ୟ: ଚାକିରି କିମ୍ବା ନିଯୁକ୍ତି?',
    companyReviews: 'କମ୍ପାନୀ ସମୀକ୍ଷା',
    sectorFilters: 'ସେକ୍ଟର ଓ ଫିଲ୍ଟର୍',
    resetFilters: 'ରିସେଟ୍',
    jobSector: 'ଚାକିରି ସେକ୍ଟର',
    allSectors: 'ସମସ୍ତ ସେକ୍ଟର',
    govtSarkari: 'ସରକାରୀ ଚାକିରି ଓ ପିଏସୟୁ',
    privateCompany: 'ପ୍ରାଇଭେଟ୍ କମ୍ପାନୀ ଚାକିରି',
    salaryRangeType: 'ଦରମା ପରିସର',
    allPayRanges: 'ସମସ୍ତ ଦରମା (ହଜାର ଓ ଲକ୍ଷ)',
    thousandsPerMonth: 'ହଜାର / ମାସିକ (₹୧୫କ - ₹୫୦କ)',
    lakhsPerAnnum: 'ଲକ୍ଷ / ବାର୍ଷିକ (₹୬ - ₹୩୦+ ଲକ୍ଷ)',
    selectStateUT: 'ରାଜ୍ୟ / କେନ୍ଦ୍ରଶାସିତ ଅଞ୍ଚଳ',
    allStatesUTs: 'ସମସ୍ତ ରାଜ୍ୟ ଓ UT',
    workLocationMode: 'କାର୍ଯ୍ୟ ସ୍ଥାନ ମୋଡ୍',
    anyMode: 'ଯେକୌଣସି ମୋଡ୍',
    onSite: 'ଅନ୍-ସାଇଟ୍ (ଅଫିସ୍)',
    workFromHome: 'ୱାର୍କ ଫ୍ରମ୍ ହୋମ୍ (ରିମୋଟ୍)',
    hybrid: 'ହାଇବ୍ରିଡ୍',
    sortBy: 'କ୍ରମ:',
    mostRecent: 'ସର୍ବଶେଷ',
    highestSalary: 'ସର୍ବାଧିକ ଦରମା',
    jobsFound: 'ଟି ଚାକିରି ମିଳିଲା',
    showingOpenPositions: 'ପାଇଁ ଖୋଲା ଚାକିରି ସୁଯୋଗ',
    featured: 'ପ୍ରମୁଖ',
    govtBadge: 'ସରକାରୀ',
    govtRegular: 'ସରକାରୀ ନିୟମିତ',
    posted: 'ପୋଷ୍ଟ ହୋଇଛି',
    applyBy: 'ଶେଷ ତାରିଖ',
    officialApply: 'ଅଫିସିଆଲ୍ ଆବେଦନ',
    saveJob: 'ସେଭ୍ କରନ୍ତୁ',
    saved: 'ସେଭ୍ ହୋଇଛି',

    whatIsYourGoal: 'ଆଜି ଆପଣଙ୍କର ମୁଖ୍ୟ ଲକ୍ଷ୍ୟ କ’ଣ?',
    iWantJob: 'ମୁଁ ଚାକିରି ଖୋଜୁଛି',
    iWantJobDesc: 'ସ୍ଥାନୀୟ ଓ ସମଗ୍ର ଭାରତରେ ଚାକିରି ଖୋଜନ୍ତୁ',
    iWantHire: 'ମୁଁ କର୍ମଚାରୀ ନିଯୁକ୍ତ କରିବାକୁ ଚାହୁଁଛି',
    iWantHireDesc: 'ଚାକିରି ପୋଷ୍ଟ କରନ୍ତୁ, ଆବେଦନକାରୀଙ୍କୁ ପରିଚାଳନା କରନ୍ତୁ',
    findGreatPlaces: 'ଶ୍ରେଷ୍ଠ କମ୍ପାନୀ ସମୀକ୍ଷା ଖୋଜନ୍ତୁ',
    getUnfilteredApp: 'କର୍ମଚାରୀଙ୍କ ନିରପେକ୍ଷ ସମୀକ୍ଷା ଓ ଦରମା ତଥ୍ୟ ଦେଖନ୍ତୁ',
    searchCompanyPlaceholder: 'କମ୍ପାନୀ ନାମ ଖୋଜନ୍ତୁ (ଯେପରି ISRO, TCS, Tata...)',
    ratings: 'ରେଟିଂ',
    reviews: 'ସମୀକ୍ଷା',
    salaries: 'ଦରମା',
    questions: 'ପ୍ରଶ୍ନୋତ୍ତର',
    openJobs: 'ଖୋଲା ଚାକିରି',
    footerDesc: 'ଭାରତର ୨୮ ରାଜ୍ୟ ଓ ଓଡ଼ିଶାର ୩୦ ଜିଲ୍ଲା ପାଇଁ ପ୍ରମୁଖ ଚାକିରି ପୋର୍ଟାଲ୍।',
    quickLinks: 'ଦ୍ରୁତ ଲିଙ୍କ୍',
    popularLocations: 'ଲୋକପ୍ରିୟ ସ୍ଥାନ',
    contactSupport: 'ଯୋଗାଯୋଗ ଓ ସହାୟତା',
    rightsReserved: 'ସମସ୍ତ ଅଧିକାର ସୁରକ୍ଷିତ।'
  },
  bn: {
    findJobs: 'চাকরি খুঁজুন',
    browseAll: 'সব দেখুন',
    myApplications: 'আমার আবেদনসমূহ',
    employerHub: 'নিয়োগকর্তা হাব',
    adminPanel: 'অ্যাডমিন প্যানেল',
    signIn: 'সাইন ইন করুন',
    postFindJobs: 'পোস্ট / চাকরি খুঁজুন',
    heroTag: '#১ সর্বভারতীয় চাকরি পোর্টাল',
    heroTitle: 'সমগ্র ভারতে আপনার স্বপ্নের ক্যারিয়ার খুঁজুন',
    heroSubtitle: 'ভারতের ২৮টি রাজ্য এবং ওড়িশার ৩০টি জেলাজুড়ে হাজার হাজার যাচাইকৃত চাকরির সুযোগ।',
    searchPlaceholder: 'চাকরির পদ, দক্ষতা, বা কোম্পানি...',
    locationPlaceholder: 'শহর, জেলা, বা রাজ্য',
    stateDistrictBtn: 'রাজ্য ও জেলা',
    searchBtn: 'চাকরি খুঁজুন',
    popularSearches: 'জনপ্রিয় অনুসন্ধান:',
    activeJobs: 'সক্রিয় চাকরি',
    verifiedEmployers: 'যাচাইকৃত নিয়োগকর্তা',
    successfulHires: 'সফল নিয়োগ',
    featuredOpenings: 'বিশেষ চাকরি',
    quickView: 'দ্রুত দেখুন',
    applyNow: 'এখনই আবেদন করুন',
    aiAssistant: 'এআই সহকারী',
    selectLanguage: 'ভাষা নির্বাচন করুন',

    goalBtn: 'লক্ষ্য: চাকরি নাকি নিয়োগ?',
    companyReviews: 'কোম্পানি রিভিউ',
    sectorFilters: 'সেক্টর ও ফিল্টার',
    resetFilters: 'রিসেট',
    jobSector: 'চাকরির ক্ষেত্র',
    allSectors: 'সমস্ত ক্ষেত্র',
    govtSarkari: 'সরকারী চাকরি ও পিএসইউ',
    privateCompany: 'বেসরকারী কোম্পানি',
    salaryRangeType: 'বেতন সীমা',
    allPayRanges: 'সমস্ত বেতন সীমা',
    thousandsPerMonth: 'হাজার / মাস (₹১৫k - ₹৫০k)',
    lakhsPerAnnum: 'লাখ / বছর (₹৬ - ₹৩০+ এলপিএ)',
    selectStateUT: 'রাজ্য / কেন্দ্রশাসিত অঞ্চল',
    allStatesUTs: 'সমস্ত রাজ্য ও অঞ্চল',
    workLocationMode: 'কাজের স্থান',
    anyMode: 'যেকোনো স্থান',
    onSite: 'অন-সাইট',
    workFromHome: 'ওয়ার্ক ফ্রম হোম',
    hybrid: 'হাইব্রিড',
    sortBy: 'সাজান:',
    mostRecent: 'সর্বশেষ',
    highestSalary: 'সর্বোচ্চ বেতন',
    jobsFound: 'টি চাকরি পাওয়া গেছে',
    showingOpenPositions: 'এর জন্য খালি পদ দেখানো হচ্ছে',
    featured: 'বিশেষ',
    govtBadge: 'সরকারী',
    govtRegular: 'সরকারী নিয়মিত',
    posted: 'পোস্টের তারিখ',
    applyBy: 'শেষ তারিখ',
    officialApply: 'অফিসিয়াল আবেদন',
    saveJob: 'সংরক্ষণ করুন',
    saved: 'সংরক্ষিত',

    whatIsYourGoal: 'আজ আপনার প্রধান লক্ষ্য কী?',
    iWantJob: 'আমি চাকরি চাই',
    iWantJobDesc: 'স্থানীয় ও সর্বভারতীয় চাকরি খুঁজুন',
    iWantHire: 'আমি কর্মী নিয়োগ করতে চাই',
    iWantHireDesc: 'চাকরি পোস্ট করুন, আবেদন পরিচালনা করুন',
    findGreatPlaces: 'সেরা কর্মক্ষেত্রের রিভিউ দেখুন',
    getUnfilteredApp: 'কর্মীদের রিভিউ ও বেতনের তথ্য দেখুন',
    searchCompanyPlaceholder: 'কোম্পানির নাম খুঁজুন (যেমন ISRO, TCS, Tata...)',
    ratings: 'রেটিং',
    reviews: 'রিভিউ',
    salaries: 'বেতন',
    questions: 'প্রশ্নাবলী',
    openJobs: 'খালি পদ',
    footerDesc: 'ভারতের ২৮টি রাজ্য এবং ওড়িশার ৩০টি জেলার জন্য প্রধান চাকরি পোর্টাল।',
    quickLinks: 'দ্রুত লিংক',
    popularLocations: 'জনপ্রিয় স্থান',
    contactSupport: 'যোগাযোগ ও সহায়তা',
    rightsReserved: 'সর্বস্বত্ব সংরক্ষিত।'
  },
  te: {
    findJobs: 'ఉద్యోగాలు వెతకండి',
    browseAll: 'అన్నీ చూడండి',
    myApplications: 'నా దరఖాస్తులు',
    employerHub: 'యజమాని హబ్',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    signIn: 'సైన్ ఇన్ చేయండి',
    postFindJobs: 'పోస్ట్ / ఉద్యోగాలు వెతకండి',
    heroTag: '#1 ఆల్ ఇండియా జాబ్ పోర్టల్',
    heroTitle: 'భారతదేశమంతటా మీ కలల కెరీర్‌ను కనుగొనండి',
    heroSubtitle: '28 రాష్ట్రాలు మరియు ఒడిశాలోని 30 జిల్లాలలో వేలాది ధృవీకరించబడిన ఉద్యోగ అవకాశాలు.',
    searchPlaceholder: 'ఉద్యోగ శీర్షిక, నైపుణ్యాలు, లేదా కంపెనీ...',
    locationPlaceholder: 'నగరం, జిల్లా, లేదా రాష్ట్రం',
    stateDistrictBtn: 'రాష్ట్రం & జిల్లా',
    searchBtn: 'ఉద్యోగాలు వెతకండి',
    popularSearches: 'ప్రజాదరణ పొందిన శోధనలు:',
    activeJobs: 'సక్రియ ఉద్యోగాలు',
    verifiedEmployers: 'ధృవీకరించబడిన యజమానులు',
    successfulHires: 'విజయవంతమైన నియామకాలు',
    featuredOpenings: 'ముఖ్యమైన ఉద్యోగాలు',
    quickView: 'త్వరిత వీక్షణ',
    applyNow: 'ఇప్పుడే దరఖాస్తు చేయండి',
    aiAssistant: 'ఏఐ అసిస్టెంట్',
    selectLanguage: 'భాషను ఎంచుకోండి',

    goalBtn: 'లక్ష్యం: ఉద్యోగమా లేదా నియామకమా?',
    companyReviews: 'కంపెనీ సమీక్షలు',
    sectorFilters: 'సెక్టార్ & ఫిల్టర్లు',
    resetFilters: 'రీసెట్',
    jobSector: 'ఉద్యోగ సెక్టార్',
    allSectors: 'అన్ని సెక్టార్లు',
    govtSarkari: 'ప్రభుత్వ ఉద్యోగాలు & పిఎస్‌యులు',
    privateCompany: 'ప్రైవేట్ కంపెనీలు',
    salaryRangeType: 'జీతం పరిధి',
    allPayRanges: 'అన్ని జీతాల పరిధులు',
    thousandsPerMonth: 'వేలు / నెల (₹15k - ₹50k)',
    lakhsPerAnnum: 'లక్షలు / సంవత్సరం (₹6 - ₹30+ LPA)',
    selectStateUT: 'రాష్ట్రం / కేంద్రపాలిత ప్రాంతం',
    allStatesUTs: 'అన్ని రాష్ట్రాలు & UTలు',
    workLocationMode: 'పని ప్రదేశం మోడ్',
    anyMode: 'ఏదైనా మోడ్',
    onSite: 'ఆన్-సైట్',
    workFromHome: 'వర్క్ ఫ్రమ్ హోమ్',
    hybrid: 'హైబ్రిడ్',
    sortBy: 'క్రమబద్ధీకరించు:',
    mostRecent: 'తాజావి',
    highestSalary: 'అత్యధిక జీతం',
    jobsFound: 'ఉద్యోగాలు కనుగొనబడ్డాయి',
    showingOpenPositions: 'కోసం అందుబాటులో ఉన్న ఖాళీలు',
    featured: 'ముఖ్యమైనవి',
    govtBadge: 'ప్రభుత్వ',
    govtRegular: 'ప్రభుత్వ క్రమబద్ధమైన',
    posted: 'పోస్ట్ చేసిన తేదీ',
    applyBy: 'చివరి తేదీ',
    officialApply: 'అధికారిక దరఖాస్తు',
    saveJob: 'సేవ్ చేయండి',
    saved: 'సేవ్ చేయబడింది',

    whatIsYourGoal: 'ఈ రోజు మీ ప్రధాన లక్ష్యం ఏమిటి?',
    iWantJob: 'నాకు ఉద్యోగం కావాలి',
    iWantJobDesc: 'స్థానిక & ఆల్ ఇండియా ఉద్యోగాలను వెతకండి',
    iWantHire: 'నేను ఉద్యోగులను నియమించాలనుకుంటున్నాను',
    iWantHireDesc: 'ఉద్యోగ ప్రకటనలను పోస్ట్ చేయండి',
    findGreatPlaces: 'ఉత్తమ కంపెనీల సమీక్షలను చూడండి',
    getUnfilteredApp: 'ఉద్యోగుల సమీక్షలు మరియు జీతం వివరాలను చూడండి',
    searchCompanyPlaceholder: 'కంపెనీ పేరు వెతకండి (ఉదా. ISRO, TCS, Tata...)',
    ratings: 'రేటింగ్స్',
    reviews: 'సమీక్షలు',
    salaries: 'జీతాలు',
    questions: 'ప్రశ్నలు',
    openJobs: 'ఉద్యోగ ఖాళీలు',
    footerDesc: '28 రాష్ట్రాలు మరియు ఒడిశాలోని 30 జిల్లాల కోసం భారతదేశపు ప్రముఖ జాబ్ పోర్టల్.',
    quickLinks: 'త్వరిత లింకులు',
    popularLocations: 'ప్రసిద్ధ ప్రాంతాలు',
    contactSupport: 'సంప్రదించండి & మద్దతు',
    rightsReserved: 'సర్వ హక్కులు ప్రత్యేకించబడ్డాయి.'
  },
  mr: {
    findJobs: 'नोकरी शोधा',
    browseAll: 'सर्व पहा',
    myApplications: 'माझे अर्ज',
    employerHub: 'नियोक्ता हब',
    adminPanel: 'ॲडमिन पॅनेल',
    signIn: 'साइन इन करा',
    postFindJobs: 'नोकरी पोस्ट / शोधा',
    heroTag: '#१ ऑल इंडिया जॉब पोर्टल',
    heroTitle: 'संपूर्ण भारतात तुमचे स्वप्नातील करिअर शोधा',
    heroSubtitle: '२८ राज्ये आणि ओडिशाच्या ३० जिल्ह्यांमध्ये हजारो सत्यापित संधी.',
    searchPlaceholder: 'नोकरीचे नाव, कौशल्य, किंवा कंपनी...',
    locationPlaceholder: 'शहर, जिल्हा, किंवा राज्य',
    stateDistrictBtn: 'राज्य आणि जिल्हा',
    searchBtn: 'नोकरी शोधा',
    popularSearches: 'लोकप्रिय शोध:',
    activeJobs: 'सक्रिय नोकऱ्या',
    verifiedEmployers: 'सत्यापित नियोक्ते',
    successfulHires: 'यशस्वी भरती',
    featuredOpenings: 'प्रमुख नोकऱ्या',
    quickView: 'झटपट पहा',
    applyNow: 'आत्ताच अर्ज करा',
    aiAssistant: 'एआय सहाय्यक',
    selectLanguage: 'भाषा निवडा',

    goalBtn: 'ध्येय: नोकरी की भरती?',
    companyReviews: 'कंपनी पुनरावलोकने',
    sectorFilters: 'क्षेत्र आणि फिल्टर',
    resetFilters: 'रीसेट',
    jobSector: 'नोकरी क्षेत्र',
    allSectors: 'सर्व क्षेत्रे',
    govtSarkari: 'सरकारी नोकरी आणि पीएसयू',
    privateCompany: 'खाजगी कंपन्या',
    salaryRangeType: 'वेतन श्रेणी',
    allPayRanges: 'सर्व वेतन श्रेणी',
    thousandsPerMonth: 'हजार / महिना (₹15k - ₹50k)',
    lakhsPerAnnum: 'लाख / वर्ष (₹6 - ₹30+ LPA)',
    selectStateUT: 'राज्य / केंद्रशासित प्रदेश',
    allStatesUTs: 'सर्व राज्ये आणि प्रदेश',
    workLocationMode: 'काम करण्याचे ठिकाण',
    anyMode: 'कोणताही प्रकार',
    onSite: 'ऑन-साइट (ऑफिस)',
    workFromHome: 'वर्क फ्रॉम होम',
    hybrid: 'हायब्रिड',
    sortBy: 'क्रमवारी:',
    mostRecent: 'नवीनतम',
    highestSalary: 'सर्वोच्च वेतन',
    jobsFound: 'नोकऱ्या सापडल्या',
    showingOpenPositions: 'मधील उपलब्ध नोकऱ्या दाखवत आहे',
    featured: 'प्रमुख',
    govtBadge: 'सरकारी',
    govtRegular: 'सरकारी नियमित',
    posted: 'पोस्ट तारीख',
    applyBy: 'अंतिम तारीख',
    officialApply: 'अधिकृत अर्ज',
    saveJob: 'सेव्ह करा',
    saved: 'सेव्ह केले',

    whatIsYourGoal: 'आज तुमचे मुख्य ध्येय काय आहे?',
    iWantJob: 'मला नोकरी हवी आहे',
    iWantJobDesc: 'स्थानिक आणि ऑल इंडिया नोकऱ्या शोधा',
    iWantHire: 'मला कर्मचारी भरती करायचे आहेत',
    iWantHireDesc: 'नोकरी पोस्ट करा, अर्ज व्यवस्थापित करा',
    findGreatPlaces: 'सर्वोत्तम कंपन्यांची पुनरावलोकने शोधा',
    getUnfilteredApp: 'कर्मचाऱ्यांची पुनरावलोकने आणि वेतन माहिती पहा',
    searchCompanyPlaceholder: 'कंपनीचे नाव शोधा (उदा. ISRO, TCS, Tata...)',
    ratings: 'रेटिंग',
    reviews: 'पुनरावलोकने',
    salaries: 'वेतन',
    questions: 'प्रश्न',
    openJobs: 'उपलब्ध नोकऱ्या',
    footerDesc: 'भारतातील २८ राज्ये आणि ओडिशाच्या ३० जिल्ह्यांसाठी प्रमुख नोकरी पोर्टल.',
    quickLinks: 'क्विक लिंक्स',
    popularLocations: 'लोकप्रिय ठिकाणे',
    contactSupport: 'संपर्क आणि मदत',
    rightsReserved: 'सर्व हक्क राखीव.'
  },
  ta: {
    findJobs: 'வேலை தேடுக',
    browseAll: 'அனைத்தும் பார்க்க',
    myApplications: 'என் விண்ணப்பங்கள்',
    employerHub: 'நிறுவனர் மையம்',
    adminPanel: 'நிர்வாகக் குழு',
    signIn: 'உள்நுழைக',
    postFindJobs: 'பதிவு / வேலை தேடுக',
    heroTag: '#1 இந்திய வேலைவாய்ப்பு தளம்',
    heroTitle: 'இந்தியா முழுவதும் உங்கள் கனவு வேலையைக் கண்டறியவும்',
    heroSubtitle: '28 மாநிலங்கள் மற்றும் ஒடிசாவின் 30 மாவட்டங்களில் ஆயிரக்கணக்கான சரிபார்க்கப்பட்ட வேலைகள்.',
    searchPlaceholder: 'வேலை தலைப்பு, திறன்கள், அல்லது நிறுவனம்...',
    locationPlaceholder: 'நகரம், மாவட்டம், அல்லது மாநிலம்',
    stateDistrictBtn: 'மாநிலம் & மாவட்டம்',
    searchBtn: 'வேலை தேடுக',
    popularSearches: 'பிரபலமான தேடல்கள்:',
    activeJobs: 'செயலில் உள்ள வேலைகள்',
    verifiedEmployers: 'சரிபார்க்கப்பட்ட நிறுவனங்கள்',
    successfulHires: 'வெற்றிகரமான நியமனங்கள்',
    featuredOpenings: 'முக்கிய வேலைகள்',
    quickView: 'விரைவுப் பார்வை',
    applyNow: 'இப்பொழுதே விண்ணப்பிக்கவும்',
    aiAssistant: 'ஏஐ உதவியாளர்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',

    goalBtn: 'இலக்கு: வேலையா அல்லது ஆள் சேர்ப்பா?',
    companyReviews: 'நிறுவன விமர்சனங்கள்',
    sectorFilters: 'துறை & வடிகட்டிகள்',
    resetFilters: 'மீட்டமை',
    jobSector: 'வேலைத் துறை',
    allSectors: 'அனைத்து துறைகளும்',
    govtSarkari: 'அரசு வேலைகள் & பொதுத்துறை',
    privateCompany: 'தனியார் நிறுவனங்கள்',
    salaryRangeType: 'சம்பள வரம்பு',
    allPayRanges: 'அனைத்து சம்பள வரம்புகளும்',
    thousandsPerMonth: 'ஆயிரம் / மாதம் (₹15k - ₹50k)',
    lakhsPerAnnum: 'லட்சம் / ஆண்டு (₹6 - ₹30+ LPA)',
    selectStateUT: 'மாநிலம் / யூனியன் பிரதேசம்',
    allStatesUTs: 'அனைத்து மாநிலங்களும்',
    workLocationMode: 'பணியிடம்',
    anyMode: 'எந்த வகையும்',
    onSite: 'நேரடி பணி',
    workFromHome: 'வீட்டிலிருந்து பணி',
    hybrid: 'ஹைபிரிட்',
    sortBy: 'வரிசைப்படுத்து:',
    mostRecent: 'சமீபத்தியவை',
    highestSalary: 'அதிக சம்பளம்',
    jobsFound: 'வேலைகள் கண்டறியப்பட்டன',
    showingOpenPositions: 'க்கான வேலை வாய்ப்புகள்',
    featured: 'முக்கியமானவை',
    govtBadge: 'அரசு',
    govtRegular: 'அரசு நிரந்தரம்',
    posted: 'பதிவிடப்பட்ட நாள்',
    applyBy: 'கடைசி நாள்',
    officialApply: 'அதிகாரப்பூர்வ விண்ணப்பம்',
    saveJob: 'சேமிக்கவும்',
    saved: 'சேமிக்கப்பட்டது',

    whatIsYourGoal: 'இன்று உங்கள் முக்கிய இலக்கு என்ன?',
    iWantJob: 'எனக்கு வேலை வேண்டும்',
    iWantJobDesc: 'உள்ளூர் & இந்திய அளவிலான வேலைகளைத் தேடுங்கள்',
    iWantHire: 'நான் ஆள் சேர்க்க விரும்புகிறேன்',
    iWantHireDesc: 'வேலை வாய்ப்புகளைப் பதிவிடுங்கள்',
    findGreatPlaces: 'சிறந்த நிறுவனங்களின் விமர்சனங்களைப் பாருங்கள்',
    getUnfilteredApp: 'ஊழியர்களின் விமர்சனங்கள் மற்றும் சம்பள விவரங்களைப் பாருங்கள்',
    searchCompanyPlaceholder: 'நிறுவனப் பெயர் தேடுக (எ.கா. ISRO, TCS, Tata...)',
    ratings: 'மதிப்பீடுகள்',
    reviews: 'விமர்சனங்கள்',
    salaries: 'சம்பளம்',
    questions: 'கேள்விகள்',
    openJobs: 'வேலை வாய்ப்புகள்',
    footerDesc: '28 மாநிலங்கள் மற்றும் ஒடிசாவின் 30 மாவட்டங்களுக்கான இந்தியாவின் முதன்மை வேலைவாய்ப்பு தளம்.',
    quickLinks: 'வேகமான இணைப்புகள்',
    popularLocations: 'பிரபலமான இடங்கள்',
    contactSupport: 'தொடர்பு & உதவி',
    rightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.'
  },
  kn: {
    findJobs: 'ಉದ್ಯೋಗ ಹುಡುಕಿ',
    browseAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    myApplications: 'ನನ್ನ ಅರ್ಜಿಗಳು',
    employerHub: 'ಉದ್ಯೋಗದಾತ ಹಬ್',
    adminPanel: 'ಅಡ್ಮಿನ್ ಪ್ಯಾನಲ್',
    signIn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    postFindJobs: 'ಪೋಸ್ಟ್ / ಹುಡುಕಿ',
    heroTag: '#1 ಆಲ್ ಇಂಡಿಯಾ ಜಾಬ್ ಪೋರ್ಟಲ್',
    heroTitle: 'ಭಾರತದಾದ್ಯಂತ ನಿಮ್ಮ ಕನಸಿನ ಉದ್ಯೋಗವನ್ನು ಕಂಡುಕೊಳ್ಳಿ',
    heroSubtitle: '28 ರಾಜ್ಯಗಳು ಮತ್ತು ಒಡಿಶಾದ 30 ಜಿಲ್ಲೆಗಳಲ್ಲಿ ಸಾವಿರಾರು ಪರಿಶೀಲಿಸಿದ ಉದ್ಯೋಗ ಅವಕಾಶಗಳು.',
    searchPlaceholder: 'ಉದ್ಯೋಗ ಶೀರ್ಷಿಕೆ, ಕೌಶಲ್ಯ, ಅಥವಾ ಕಂಪನಿ...',
    locationPlaceholder: 'ನಗರ, ಜಿಲ್ಲೆ, ಅಥವಾ ರಾಜ್ಯ',
    stateDistrictBtn: 'ರಾಜ್ಯ ಮತ್ತು ಜಿಲ್ಲೆ',
    searchBtn: 'ಉದ್ಯೋಗ ಹುಡುಕಿ',
    popularSearches: 'ಜನಪ್ರಿಯ ಹುಡುಕಾಟಗಳು:',
    activeJobs: 'ಸಕ್ರಿಯ ಉದ್ಯೋಗಗಳು',
    verifiedEmployers: 'ಪರಿಶೀಲಿಸಿದ ಉದ್ಯೋಗದಾತರು',
    successfulHires: 'ಯಶಸ್ವಿ ನೇಮಕಾತಿಗಳು',
    featuredOpenings: 'ಪ್ರಮುಖ ಉದ್ಯೋಗಗಳು',
    quickView: 'ತ್ವರಿತ ನೋಟ',
    applyNow: 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    aiAssistant: 'ಎಐ ಸಹಾಯಕ',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',

    goalBtn: 'ಗುರಿ: ಉದ್ಯೋಗವೇ ಅಥವಾ ನೇಮಕಾತಿಯೇ?',
    companyReviews: 'ಕಂಪನಿ ವಿಮರ್ಶೆಗಳು',
    sectorFilters: 'ವಲಯ & ಫಿಲ್ಟರ್‌ಗಳು',
    resetFilters: 'ರೀಸೆಟ್',
    jobSector: 'ಉದ್ಯೋಗ ವಲಯ',
    allSectors: 'ಎಲ್ಲಾ ವಲಯಗಳು',
    govtSarkari: 'ಸರ್ಕಾರಿ ಉದ್ಯೋಗಗಳು & ಪಿಎಸ್‌ಯುಗಳು',
    privateCompany: 'ಖಾಸಗಿ ಕಂಪನಿಗಳು',
    salaryRangeType: 'ವೇತನ ಶ್ರೇಣಿ',
    allPayRanges: 'ಎಲ್ಲಾ ವೇತನ ಶ್ರೇಣಿಗಳು',
    thousandsPerMonth: 'ಸಾಕಷ್ಟು / ತಿಂಗಳು (₹15k - ₹50k)',
    lakhsPerAnnum: 'ಲಕ್ಷ / ವರ್ಷ (₹6 - ₹30+ LPA)',
    selectStateUT: 'ರಾಜ್ಯ / ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶ',
    allStatesUTs: 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು & UTಗಳು',
    workLocationMode: 'ಕೆಲಸದ ಸ್ಥಳ',
    anyMode: 'ಯಾವುದೇ ವಿಧಾನ',
    onSite: 'ಆನ್-ಸೈಟ್',
    workFromHome: 'ವರ್ಕ್ ಫ್ರಮ್ ಹೋಮ್',
    hybrid: 'ಹೈಬ್ರಿಡ್',
    sortBy: 'ವಿಂಗಡಿಸಿ:',
    mostRecent: 'ಇತ್ತೀಚಿನವು',
    highestSalary: 'ಹೆಚ್ಚಿನ ವೇತನ',
    jobsFound: 'ಉದ್ಯೋಗಗಳು ಸಿಕ್ಕಿವೆ',
    showingOpenPositions: 'ಗಾಗಿ ಲಭ್ಯವಿರುವ ಉದ್ಯೋಗಗಳು',
    featured: 'ಪ್ರಮುಖ',
    govtBadge: 'ಸರ್ಕಾರಿ',
    govtRegular: 'ಸರ್ಕಾರಿ ಖಾಯಂ',
    posted: 'ಪೋಸ್ಟ್ ಮಾಡಿದ ದಿನಾಂಕ',
    applyBy: 'ಕೊನೆಯ ದಿನಾಂಕ',
    officialApply: 'ಅಧಿಕೃತ ಅರ್ಜಿ',
    saveJob: 'ಸೇವ್ ಮಾಡಿ',
    saved: 'ಸೇವ್ ಆಗಿದೆ',

    whatIsYourGoal: 'ಇಂದು ನಿಮ್ಮ ಮುಖ್ಯ ಗುರಿ ಏನು?',
    iWantJob: 'ನನಗೆ ಉದ್ಯೋಗ ಬೇಕು',
    iWantJobDesc: 'ಸ್ಥಳೀಯ & ಭಾರತದಾದ್ಯಂತ ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ',
    iWantHire: 'ನಾನು ಅಭ್ಯರ್ಥಿಗಳನ್ನು ನೇಮಿಸಿಕೊಳ್ಳಲು ಬಯಸುತ್ತೇನೆ',
    iWantHireDesc: 'ಉದ್ಯೋಗ ಪೋಸ್ಟ್ ಮಾಡಿ',
    findGreatPlaces: 'ಉತ್ತಮ ಕಂಪನಿಗಳ ವಿಮರ್ಶೆಗಳನ್ನು ನೋಡಿ',
    getUnfilteredApp: 'ಉದ್ಯೋಗಿಗಳ ವಿಮರ್ಶೆಗಳು ಮತ್ತು ವೇತನ ವಿವರಗಳನ್ನು ನೋಡಿ',
    searchCompanyPlaceholder: 'ಕಂಪನಿ ಹೆಸರು ಹುಡುಕಿ (ಉದಾ. ISRO, TCS, Tata...)',
    ratings: 'ರೇಟಿಂಗ್‌ಗಳು',
    reviews: 'ವಿಮರ್ಶೆಗಳು',
    salaries: 'ವೇತನ',
    questions: 'ಪ್ರಶ್ನೆಗಳು',
    openJobs: 'ಲಭ್ಯವಿರುವ ಉದ್ಯೋಗಗಳು',
    footerDesc: '28 ರಾಜ್ಯಗಳು ಮತ್ತು ಒಡಿಶಾದ 30 ಜಿಲ್ಲೆಗಳಿಗಾಗಿ ಭಾರತದ ಪ್ರಮುಖ ಉದ್ಯೋಗ ಪೋರ್ಟಲ್.',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    popularLocations: 'ಜನಪ್ರಿಯ ಸ್ಥಳಗಳು',
    contactSupport: 'ಸಂಪರ್ಕ & ಬೆಂಬಲ',
    rightsReserved: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.'
  },
  gu: {
    findJobs: 'નોકરી શોધો',
    browseAll: 'બધું જુઓ',
    myApplications: 'મારી અરજીઓ',
    employerHub: 'એમ્પ્લોયર હબ',
    adminPanel: 'એડમિન પેનલ',
    signIn: 'સાઇન ઇન કરો',
    postFindJobs: 'પોસ્ટ / નોકરી શોધો',
    heroTag: '#1 ઓલ ઈન્ડિયા જોબ પોર્ટલ',
    heroTitle: 'સમગ્ર ભારતમાં તમારી ડ્રીમ કેરિયર શોધો',
    heroSubtitle: '૨૮ રાજ્યો અને ઓડિશાના ૩૦ જિલ્લાઓમાં હજારો ચકાસાયેલ તકો.',
    searchPlaceholder: 'જોબ ટાઇટલ, સ્કીલ, અથવા કંપની...',
    locationPlaceholder: 'શહેર, જિલ્લો, અથવા રાજ્ય',
    stateDistrictBtn: 'રાજ્ય અને જિલ્લો',
    searchBtn: 'નોકરી શોધો',
    popularSearches: 'લોકપ્રિય શોધો:',
    activeJobs: 'સક્રિય નોકરીઓ',
    verifiedEmployers: 'ચકાસાયેલ એમ્પ્લોયરો',
    successfulHires: 'સફળ ભરતી',
    featuredOpenings: 'મુખ્ય નોકરીઓ',
    quickView: 'ઝડપી જુઓ',
    applyNow: 'હમણાં અરજી કરો',
    aiAssistant: 'એઆઈ સહાયક',
    selectLanguage: 'ભાષા પસંદ કરો',

    goalBtn: 'ધ્યેય: નોકરી કે ભરતી?',
    companyReviews: 'કંપની સમીક્ષાઓ',
    sectorFilters: 'સેક્ટર અને ફિલ્ટર્સ',
    resetFilters: 'રીસેટ',
    jobSector: 'નોકરી ક્ષેત્ર',
    allSectors: 'તમામ ક્ષેત્રો',
    govtSarkari: 'સરકારી નોકરી અને પીએસયુ',
    privateCompany: 'ખાનગી કંપનીઓ',
    salaryRangeType: 'પગાર મર્યાદા',
    allPayRanges: 'તમામ પગાર મર્યાદાઓ',
    thousandsPerMonth: 'હજાર / મહિનો (₹15k - ₹50k)',
    lakhsPerAnnum: 'લાખ / વર્ષ (₹6 - ₹30+ LPA)',
    selectStateUT: 'રાજ્ય / કેન્દ્રશાસિત પ્રદેશ',
    allStatesUTs: 'તમામ રાજ્યો અને પ્રદેશો',
    workLocationMode: 'કામનું સ્થળ',
    anyMode: 'કોઈપણ મોડ',
    onSite: 'ઓન-સાઇટ',
    workFromHome: 'વર્ક ફ્રોમ હોમ',
    hybrid: 'હાઇબ્રિડ',
    sortBy: 'ક્રમ:',
    mostRecent: 'નવીનતમ',
    highestSalary: 'સૌથી વધુ પગાર',
    jobsFound: 'નોકરીઓ મળી',
    showingOpenPositions: 'માટે ખાલી જગ્યાઓ દર્શાવે છે',
    featured: 'મુખ્ય',
    govtBadge: 'સરકારી',
    govtRegular: 'સરકારી નિયમિત',
    posted: 'પોસ્ટ તારીખ',
    applyBy: 'છેલ્લી તારીખ',
    officialApply: 'સત્તાવાર અરજી',
    saveJob: 'સેવ કરો',
    saved: 'સેવ થયું',

    whatIsYourGoal: 'આજે તમારું મુખ્ય ધ્યેય શું છે?',
    iWantJob: 'મને નોકરી જોઈએ છે',
    iWantJobDesc: 'સ્થાનિક અને ઓલ ઈન્ડિયા નોકરીઓ શોધો',
    iWantHire: 'હું કર્મચારીઓ રાખવા માંગુ છું',
    iWantHireDesc: 'નોકરીની જાહેરાત પોસ્ટ કરો',
    findGreatPlaces: 'શ્રેષ્ઠ કંપનીઓની સમીક્ષાઓ જુઓ',
    getUnfilteredApp: 'કર્મચારીઓની સમીક્ષાઓ અને પગારની વિગતો જુઓ',
    searchCompanyPlaceholder: 'કંપનીનું નામ શોધો (જેમ કે ISRO, TCS, Tata...)',
    ratings: 'રેટિંગ્સ',
    reviews: 'સમીક્ષાઓ',
    salaries: 'પગાર',
    questions: 'પ્રશ્નો',
    openJobs: 'ખાલી જગ્યાઓ',
    footerDesc: '૨૮ રાજ્યો અને ઓડિશાના ૩૦ જિલ્લાઓ માટે ભારતનું અગ્રણી જોબ પોર્ટલ.',
    quickLinks: 'ઝડપી લિંક્સ',
    popularLocations: 'લોકપ્રિય સ્થળો',
    contactSupport: 'સંપર્ક અને મદદ',
    rightsReserved: 'તમામ હકો અનામત.'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('jobseeker_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('jobseeker_lang', lang);
  }, [lang]);

  const t = (key, fallbackText) => {
    const langDict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    if (langDict && langDict[key]) return langDict[key];
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) return TRANSLATIONS.en[key];
    return fallbackText || key;
  };

  const changeLanguage = (code) => {
    setLang(code);
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

